import { useState } from 'react';
import { motion } from 'framer-motion';
import { notifyUser } from '@/lib/mobileFeedback';

type Axis='EI'|'SN'|'TF'|'JP';
type Figure='다니엘'|'요셉'|'룻'|'바나바'|'베드로'|'느헤미야'|'에스더'|'디모데'|'다윗'|'마리아';
type Option={text:string;side:0|1;figure:Figure};
type Question={axis:Axis;question:string;options:Option[]};
const questions:Question[]=[
{axis:'EI',question:'학생회 모임에서 갑자기 진행을 맡게 된다면?',options:[{text:'바로 앞으로 나가 분위기를 이끈다',side:0,figure:'베드로'},{text:'잠깐 마음을 가다듬고 준비한다',side:1,figure:'다니엘'},{text:'친구들과 역할을 나눠 함께 진행한다',side:0,figure:'바나바'},{text:'상황을 살피며 필요한 부분부터 돕는다',side:1,figure:'마리아'}]},
{axis:'SN',question:'학생회에서 새로운 행사를 준비할 때 나는?',options:[{text:'새로운 아이디어와 전체 분위기를 먼저 떠올린다',side:0,figure:'에스더'},{text:'준비물과 순서를 먼저 확인한다',side:1,figure:'느헤미야'},{text:'친구들이 즐겁게 참여할 모습을 상상한다',side:0,figure:'다윗'},{text:'지금 필요한 일을 하나씩 정리한다',side:1,figure:'요셉'}]},
{axis:'TF',question:'친구가 모임에서 힘들어 보일 때 나는?',options:[{text:'먼저 마음을 물어보고 공감한다',side:0,figure:'바나바'},{text:'필요한 것을 듣고 해결 방법을 찾는다',side:1,figure:'요셉'},{text:'말하지 않아도 곁에서 편하게 있어 준다',side:0,figure:'룻'},{text:'상황을 정리해 현실적인 도움을 준다',side:1,figure:'다니엘'}]},
{axis:'JP',question:'예배와 학생회 활동이 겹쳐 할 일이 많다면?',options:[{text:'시간과 순서를 정해 하나씩 끝낸다',side:0,figure:'느헤미야'},{text:'그때 가장 급한 일부터 처리한다',side:1,figure:'베드로'},{text:'친구들과 역할을 정해 미리 준비한다',side:0,figure:'디모데'},{text:'상황에 따라 계획을 바꾸며 움직인다',side:1,figure:'다윗'}]},
{axis:'EI',question:'새로 함께하게 된 친구가 어색해 보인다면?',options:[{text:'먼저 말을 걸어 자연스럽게 함께한다',side:0,figure:'바나바'},{text:'부담스럽지 않게 곁에서 기다린다',side:1,figure:'마리아'},{text:'다른 친구들과 함께할 수 있게 연결한다',side:0,figure:'에스더'},{text:'필요한 순간에 조용히 챙긴다',side:1,figure:'룻'}]},
{axis:'SN',question:'학생회에서 맡은 일을 할 때 더 중요하게 생각하는 것은?',options:[{text:'이 일이 공동체에 어떤 변화를 만들지 생각한다',side:0,figure:'에스더'},{text:'실수 없이 필요한 일을 제대로 해낸다',side:1,figure:'요셉'},{text:'좋은 분위기와 의미 있는 순간을 만든다',side:0,figure:'다윗'},{text:'작은 일도 맡은 부분을 정확히 끝낸다',side:1,figure:'디모데'}]},
{axis:'TF',question:'친구들과 의견이 갈렸을 때 나는?',options:[{text:'서로 상처받지 않도록 마음부터 살핀다',side:0,figure:'룻'},{text:'각 의견의 장단점을 비교한다',side:1,figure:'다니엘'},{text:'모두가 다시 함께할 방법을 찾는다',side:0,figure:'바나바'},{text:'원칙과 해야 할 일을 기준으로 정리한다',side:1,figure:'느헤미야'}]},
{axis:'JP',question:'학생회에서 작은 실수가 생겼다면?',options:[{text:'다음에는 같은 일이 없도록 방법을 정리한다',side:0,figure:'요셉'},{text:'일단 수습하고 다음 일로 넘어간다',side:1,figure:'베드로'},{text:'다시 계획을 세워 차분하게 보완한다',side:0,figure:'디모데'},{text:'상황에 맞는 방법으로 바꾼다',side:1,figure:'다윗'}]},
{axis:'EI',question:'학생회 활동을 마친 뒤 가장 뿌듯한 순간은?',options:[{text:'친구들과 함께 웃으며 좋은 시간을 보냈을 때',side:0,figure:'다윗'},{text:'조용히 맡은 일을 끝까지 해냈을 때',side:1,figure:'마리아'},{text:'누군가가 힘을 얻고 다시 참여했을 때',side:0,figure:'바나바'},{text:'내가 맡은 부분이 깔끔하게 마무리됐을 때',side:1,figure:'다니엘'}]},
{axis:'SN',question:'한 주 동안 학생회 활동을 돌아볼 때 나는?',options:[{text:'다음에는 어떤 새로운 모습을 만들지 생각한다',side:0,figure:'에스더'},{text:'잘된 점과 부족했던 일을 구체적으로 정리한다',side:1,figure:'요셉'},{text:'함께했던 사람들과의 의미를 먼저 떠올린다',side:0,figure:'룻'},{text:'다음 주에 해야 할 일을 정리해 둔다',side:1,figure:'느헤미야'}]}
];
const profiles:Record<Figure,{title:string;desc:string;strength:string;verse:string;ref:string;practice:string}>=
{다니엘:{title:'흔들리지 않는 중심의 다니엘형',desc:'차분하게 상황을 판단하고 자신의 기준을 지키는 모습이 다니엘과 닮았습니다.',strength:'신중함 · 책임감 · 꾸준함',ref:'다니엘 6:10',verse:'그의 하나님께 감사하였더라',practice:'이번 주에 정한 시간에 말씀과 기도를 꾸준히 이어가 보세요.'},요셉:{title:'지혜롭게 준비하는 요셉형',desc:'현실적인 방법을 찾고 맡은 일을 차근차근 준비하는 모습이 요셉과 닮았습니다.',strength:'성실함 · 준비성 · 문제해결',ref:'창세기 39:23',verse:'여호와께서 요셉과 함께 하심이라',practice:'학생회에서 필요한 일 하나를 미리 준비해 보세요.'},룻:{title:'끝까지 함께하는 룻형',desc:'관계를 소중히 여기고 가까운 사람을 꾸준히 돌보는 모습이 룻과 닮았습니다.',strength:'배려 · 충성 · 섬김',ref:'룻기 1:16',verse:'어머니의 하나님이 나의 하나님이 되시리니',practice:'이번 주에 한 친구의 이야기를 먼저 들어 주세요.'},바나바:{title:'사람을 살리는 바나바형',desc:'사람의 장점을 발견하고 함께 성장하도록 돕는 모습이 바나바와 닮았습니다.',strength:'격려 · 관계 · 공동체성',ref:'사도행전 11:24',verse:'성령과 믿음이 충만한 자라',practice:'친구 한 명의 장점을 구체적으로 말해 주세요.'},베드로:{title:'먼저 움직이는 베드로형',desc:'생각에만 머물지 않고 먼저 행동하며 경험 속에서 배우는 모습이 베드로와 닮았습니다.',strength:'실행력 · 열정 · 회복력',ref:'요한복음 21:17',verse:'내가 주님을 사랑하는 줄을 주님께서 아시나이다',practice:'미루고 있던 작은 섬김 하나를 오늘 시작해 보세요.'},느헤미야:{title:'공동체를 세우는 느헤미야형',desc:'문제를 발견하고 필요한 일을 정리해 공동체가 움직이게 하는 모습이 느헤미야와 닮았습니다.',strength:'계획 · 책임 · 조직력',ref:'느헤미야 2:20',verse:'우리가 일어나 건축하려니와',practice:'학생회에서 반복되는 불편 하나의 해결 방법을 제안해 보세요.'},에스더:{title:'용기 있게 때를 분별하는 에스더형',desc:'필요한 순간에 용기를 내어 공동체를 위해 행동하는 모습이 에스더와 닮았습니다.',strength:'용기 · 분별력 · 헌신',ref:'에스더 4:14',verse:'이 때를 위함이 아닌지 누가 알겠느냐',practice:'이번 주에 피하지 않고 먼저 맡아 볼 작은 역할을 정해 보세요.'},디모데:{title:'작은 자리에서 꾸준히 자라는 디모데형',desc:'맡은 자리에서 배우고 성실하게 성장하는 모습이 디모데와 닮았습니다.',strength:'꾸준함 · 배움 · 성실함',ref:'디모데전서 4:12',verse:'믿는 자에게 본이 되어',practice:'한 가지 좋은 습관을 정하고 7일 동안 이어가 보세요.'},다윗:{title:'마음과 열정으로 움직이는 다윗형',desc:'기쁨과 열정으로 함께하고 자신의 마음을 솔직하게 표현하는 모습이 다윗과 닮았습니다.',strength:'열정 · 기쁨 · 솔직함',ref:'시편 16:8',verse:'내가 흔들리지 아니하리로다',practice:'이번 주에 감사한 일을 세 가지 적어 보세요.'},마리아:{title:'말씀을 마음에 간직하는 마리아형',desc:'중요한 것을 마음에 담고 깊이 생각하며 조용히 섬기는 모습이 마리아와 닮았습니다.',strength:'깊이 · 차분함 · 묵상',ref:'누가복음 2:19',verse:'마음에 새기어 생각하니라',practice:'말씀 한 구절을 골라 하루 동안 마음에 새겨 보세요.'}};
const order:Figure[]=['다니엘','요셉','룻','바나바','베드로','느헤미야','에스더','디모데','다윗','마리아'];
function result(answers:string[]){const axes:Record<Axis,number>={EI:0,SN:0,TF:0,JP:0};const scores=Object.fromEntries(order.map(x=>[x,0])) as Record<Figure,number>;answers.forEach((a,i)=>{const o=questions[i].options.find(x=>x.text===a);if(!o)return;axes[questions[i].axis]+=o.side? -1:1;scores[o.figure]++;});const type=`${axes.EI>=0?'E':'I'}${axes.SN>=0?'N':'S'}${axes.TF>=0?'F':'T'}${axes.JP>=0?'J':'P'}`;const figure=order.reduce((a,b)=>scores[b]>scores[a]?b:a,order[0]);return {type,figure,profile:profiles[figure]};}
export default function BibleMbtiEnhanced(){const[step,setStep]=useState(0);const[answers,setAnswers]=useState<string[]>([]);const[data,setData]=useState<ReturnType<typeof result>|null>(null);const choose=(text:string)=>{const next=[...answers,text];setAnswers(next);if(step<9)setStep(step+1);else setData(result(next));};const reset=()=>{setStep(0);setAnswers([]);setData(null)};return <div className="min-h-screen bg-background-50"><div className="mx-auto max-w-2xl px-4 py-8 md:py-14 pb-28">{!data?<><header className="text-center mb-8"><div className="mx-auto mb-4 flex h-16 w-16 items-center justify-center rounded-[22px] bg-primary-100 border border-primary-200"><i className="ri-book-mark-line text-3xl text-primary-600"/></div><h1 className="text-2xl md:text-3xl font-black text-foreground-950">말씀 MBTI</h1><p className="mt-2 text-sm text-foreground-600">학생회에서 겪을 만한 10가지 상황에 답하고 나와 닮은 성경 인물을 찾아보세요.</p></header><div className="mb-5"><div className="flex justify-between text-xs text-foreground-500 mb-2"><span>{step+1} / 10</span><span>{Math.round((step/10)*100)}%</span></div><div className="h-2 rounded-full bg-background-200 overflow-hidden"><div className="h-full bg-primary-500 rounded-full" style={{width:`${(step/10)*100}%`}}/></div></div><motion.div key={step} initial={{opacity:0,x:20}} animate={{opacity:1,x:0}} className="rounded-[22px] border border-background-200 bg-background-100 p-5 md:p-7"><p className="text-sm font-bold text-primary-600 mb-3">질문 {step+1}</p><h2 className="text-xl md:text-2xl font-bold text-foreground-950 leading-relaxed mb-6">{questions[step].question}</h2><div className="grid gap-3">{questions[step].options.map(o=><button key={o.text} type="button" onClick={()=>choose(o.text)} className="w-full min-h-14 rounded-2xl border border-background-200 bg-background-50 px-4 py-3 text-left text-sm font-semibold text-foreground-800 hover:border-primary-300 hover:bg-primary-50 active:scale-[.99] transition-colors">{o.text}</button>)}</div>{step>0&&<button type="button" onClick={()=>{setStep(step-1);setAnswers(a=>a.slice(0,-1))}} className="mt-5 min-h-10 text-sm text-foreground-500">이전 질문</button>}</motion.div></>:<ResultView data={data} reset={reset}/>}</div></div>}
function ResultView({data,reset}:{data:NonNullable<ReturnType<typeof result>>;reset:()=>void}){const p=data.profile;const share=async()=>{const text=`말씀 MBTI · ${data.figure}\n${p.title}\n${p.desc}\n${p.ref}`;try{if(navigator.share)await navigator.share({title:'말씀 MBTI 결과',text});else await navigator.clipboard.writeText(text);notifyUser('결과를 공유할 준비가 되었어요.')}catch{}};return <motion.div initial={{opacity:0,y:15}} animate={{opacity:1,y:0}} className="space-y-4"><section className="rounded-[24px] bg-background-100 border border-background-200 p-6 md:p-8 text-center"><span className="inline-flex rounded-full bg-primary-100 px-3 py-1 text-xs font-black text-primary-700">나의 MBTI · {data.type}</span><p className="mt-5 text-sm font-bold text-primary-600">나와 닮은 성경 인물</p><h2 className="mt-1 text-3xl md:text-4xl font-black text-foreground-950">{data.figure}</h2><h3 className="mt-2 text-lg font-bold text-foreground-800">{p.title}</h3><p className="mt-4 text-sm leading-relaxed text-foreground-700">{p.desc}</p></section><section className="rounded-[22px] bg-background-100 border border-background-200 p-5"><h3 className="font-bold text-foreground-950">이런 점이 닮았어요</h3><p className="mt-3 text-sm text-foreground-700">{p.strength}</p></section><section className="rounded-[22px] bg-primary-50 border border-primary-100 p-5"><p className="text-xs font-bold text-primary-700">추천 말씀 · {p.ref}</p><p className="mt-2 font-quote text-base leading-relaxed text-primary-950">“{p.verse}”</p></section><section className="rounded-[22px] bg-background-100 border border-background-200 p-5"><h3 className="font-bold text-foreground-950">이번 주 실천</h3><p className="mt-2 text-sm leading-relaxed text-foreground-700">{p.practice}</p></section><div className="grid grid-cols-2 gap-3"><button type="button" onClick={reset} className="min-h-12 rounded-xl border border-background-200 bg-background-100 text-sm font-bold text-foreground-700">다시 검사</button><button type="button" onClick={share} className="min-h-12 rounded-xl bg-primary-500 text-white text-sm font-bold">공유하기</button></div></motion.div>}
