import { useEffect, useMemo, useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { useAuth } from '@/hooks/useAuth';
import { supabase } from '@/lib/supabase';
import DiaryComposer from '@/pages/faithJournal/components/DiaryComposer';
import AiQuestions from '@/pages/faithJournal/components/AiQuestions';
import WeeklySummary from '@/pages/faithJournal/components/WeeklySummary';
import { buildDiaryDays, buildWeekEntries, computeStreak, formatDiaryDate, formatWeekLabel, getWeekDays, MOODS, STORY_TYPES, type DiaryFilter, type FaithEntry, type RepentanceEntry, type StoryEvent } from '@/pages/faithJournal/lib';

const FILTERS:{key:DiaryFilter;label:string;icon:string}[]=[
 {key:'all',label:'전체',icon:'ri-layout-grid-line'},
 {key:'journal',label:'말씀 묵상',icon:'ri-book-open-line'},
 {key:'moment',label:'신앙의 순간',icon:'ri-star-line'},
 {key:'repentance',label:'회개와 기도',icon:'ri-hand-heart-line'},
];

export default function FaithJournal(){
 const {user}=useAuth();
 const [journals,setJournals]=useState<FaithEntry[]>([]),[moments,setMoments]=useState<StoryEvent[]>([]),[repentances,setRepentances]=useState<RepentanceEntry[]>([]);
 const [loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[showComposer,setShowComposer]=useState(false),[filter,setFilter]=useState<DiaryFilter>('all');
 const [confirmDelete,setConfirmDelete]=useState<{kind:'journal'|'moment'|'repentance';id:string;photoUrl?:string|null}|null>(null);

 const load=async()=>{if(!user)return;setLoading(true);setError(null);try{const [j,m,r]=await Promise.all([
  supabase.from('faith_journal_entries').select('*').eq('user_id',user.id),
  supabase.from('faith_storybooks').select('*').eq('author_id',user.id),
  supabase.from('repentance_journals').select('*').eq('author_id',user.id),
 ]);if(j.error)throw j.error;if(m.error)throw m.error;if(r.error)throw r.error;setJournals((j.data||[]) as FaithEntry[]);setMoments((m.data||[]) as StoryEvent[]);setRepentances((r.data||[]) as RepentanceEntry[]);}catch{setError('신앙일기를 불러오지 못했어요. 잠시 후 다시 시도해주세요.')}finally{setLoading(false)}};
 useEffect(()=>{if(user)void load();else setLoading(false)},[user]);

 const days=useMemo(()=>buildDiaryDays(journals,moments,repentances),[journals,moments,repentances]);
 const filtered=useMemo(()=>filter==='all'?days:days.filter(d=>filter==='journal'?d.journals.length>0:filter==='moment'?d.moments.length>0:d.repentances.length>0),[days,filter]);
 const week=useMemo(()=>getWeekDays(),[]),weekEntries=useMemo(()=>buildWeekEntries(days,week.days),[days,week.days]);
 const stats=useMemo(()=>({total:days.length,streak:computeStreak(days.map(d=>d.date)),thisMonth:days.filter(d=>d.date.startsWith(new Date().getFullYear()+'-'+String(new Date().getMonth()+1).padStart(2,'0'))).length}),[days]);

 const remove=async()=>{if(!confirmDelete)return;const {kind,id,photoUrl}=confirmDelete;try{
  if(kind==='journal'){const r=await supabase.from('faith_journal_entries').delete().eq('id',id);if(r.error)throw r.error;setJournals(p=>p.filter(x=>x.id!==id))}
  else if(kind==='moment'){if(photoUrl){try{const url=new URL(photoUrl);const parts=url.pathname.split('/');const i=parts.findIndex(p=>p==='Public');if(i>=0)await supabase.storage.from('Public').remove([parts.slice(i+1).join('/')])}catch{}}const r=await supabase.from('faith_storybooks').delete().eq('id',id);if(r.error)throw r.error;setMoments(p=>p.filter(x=>x.id!==id))}
  else{const r=await supabase.from('repentance_journals').delete().eq('id',id);if(r.error)throw r.error;setRepentances(p=>p.filter(x=>x.id!==id))}
 }catch{setError('삭제 중 문제가 발생했어요. 잠시 후 다시 시도해주세요.')}finally{setConfirmDelete(null)}};

 return <div className="min-h-screen bg-background-50"><div className="mx-auto max-w-2xl px-4 py-8 md:px-6 md:py-12">
  <motion.div initial={{opacity:0,y:16}} animate={{opacity:1,y:0}}>
   <header className="mb-6 text-center"><div className="mx-auto mb-4 flex h-16 w-16 items-center justify-center rounded-card bg-gradient-to-br from-primary-500 to-accent-500"><i className="ri-book-2-line text-3xl text-background-50"/></div><h1 className="text-2xl font-black text-foreground-950 md:text-3xl">신앙일기</h1><p className="mt-2 text-sm leading-6 text-foreground-600">말씀 묵상 · 신앙의 순간 · 회개와 기도를<br className="md:hidden"/> 한 곳에 기록해보세요.</p><p className="mt-2 inline-flex items-center gap-1 text-[11px] text-foreground-400"><i className="ri-lock-line"/>나만 볼 수 있는 비공개 기록이에요</p></header>
   <div className="mb-6 grid grid-cols-3 gap-2.5"><div className="rounded-card bg-gradient-to-br from-primary-500 to-accent-500 p-4 text-center"><p className="text-2xl font-black text-background-50">{stats.streak}</p><p className="mt-1 text-[11px] font-semibold text-background-50/80">연속 기록일</p></div><div className="rounded-card border border-background-200 bg-background-100 p-4 text-center"><p className="text-2xl font-black text-primary-600">{stats.thisMonth}</p><p className="mt-1 text-[11px] font-semibold text-foreground-500">이번 달 기록</p></div><div className="rounded-card border border-background-200 bg-background-100 p-4 text-center"><p className="text-2xl font-black text-foreground-950">{stats.total}</p><p className="mt-1 text-[11px] font-semibold text-foreground-500">전체 기록</p></div></div>
   {error&&<div className="mb-5 rounded-card border border-accent-200 bg-accent-50 p-4 text-sm text-accent-700"><i className="ri-error-warning-line mr-2"/>{error}<button onClick={()=>void load()} className="ml-3 font-semibold underline cursor-pointer">다시 시도</button></div>}
   <button onClick={()=>setShowComposer(true)} className="mb-6 flex min-h-12 w-full items-center justify-center gap-2 rounded-card bg-primary-500 px-4 py-4 text-sm font-bold text-background-50 hover:bg-primary-600 cursor-pointer"><i className="ri-quill-pen-line"/>오늘의 신앙일기 쓰기</button>
   <div className="mb-6"><AiQuestions/></div>
   <div className="mb-6"><WeeklySummary entries={weekEntries} weekLabel={formatWeekLabel(week.start,week.end)}/></div>
   <div className="mb-6 flex gap-1 overflow-x-auto rounded-chip border border-background-200 bg-background-100 p-1">{FILTERS.map(f=><button key={f.key} onClick={()=>setFilter(f.key)} className={'flex min-h-10 shrink-0 flex-1 items-center justify-center gap-1.5 rounded-chip px-3 py-2 text-xs font-semibold whitespace-nowrap cursor-pointer '+(filter===f.key?'bg-primary-500 text-background-50':'text-foreground-500 hover:text-foreground-800')}><i className={f.icon}/>{f.label}</button>)}</div>
   {loading?<div className="py-16 text-center"><i className="ri-loader-4-line animate-spin text-2xl text-primary-500"/></div>:filtered.length===0?<div className="rounded-card border border-dashed border-background-300 bg-background-100 py-16 text-center"><i className="ri-book-open-line text-3xl text-primary-300"/><p className="mt-3 text-sm font-bold text-foreground-700">{days.length===0?'아직 기록이 없어요.':'이 항목의 기록이 아직 없어요.'}</p><p className="mt-1 text-xs text-foreground-500">오늘의 신앙일기를 써보세요.</p></div>:<div className="relative pl-5"><div className="absolute left-[7px] top-2 bottom-2 w-px bg-primary-100"/><div className="space-y-4">{filtered.map((day,index)=><motion.article key={day.date} initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} transition={{delay:Math.min(index,8)*.04}} className="relative"><div className="absolute -left-5 top-4 h-3.5 w-3.5 rounded-chip border-2 border-background-50 bg-primary-400"/><div className="rounded-card border border-background-200 bg-background-100 p-5 shadow-card"><div className="mb-4 flex items-center justify-between gap-3"><span className="flex items-center gap-2 text-xs font-bold text-primary-600"><i className="ri-calendar-line"/>{formatDiaryDate(day.date)}</span></div>
    {day.journals.map(j=><div key={j.id} className="mb-3 rounded-input border border-primary-100 bg-primary-50/60 p-4"><div className="mb-2 flex items-center justify-between"><span className={'inline-flex items-center gap-1 rounded-chip border px-2 py-1 text-[11px] font-semibold '+(MOODS[j.mood]?.chip||'bg-background-200 text-foreground-600')}><i className={MOODS[j.mood]?.icon}/>{MOODS[j.mood]?.label}</span><button onClick={()=>setConfirmDelete({kind:'journal',id:j.id})} className="flex h-9 w-9 items-center justify-center text-foreground-300 hover:text-accent-600 cursor-pointer"><i className="ri-delete-bin-line"/></button></div>{j.scripture&&<div className="mb-2 rounded-input border border-primary-100 bg-background-100 px-3 py-2"><p className="font-quote text-sm leading-6 text-primary-800">{j.scripture}</p></div>}<p className="whitespace-pre-wrap text-sm leading-7 text-foreground-700">{j.content}</p></div>)}
    {day.moments.map(m=><div key={m.id} className="mb-3 rounded-input border border-accent-100 bg-accent-50/60 p-4"><div className="mb-2 flex items-center justify-between"><span className="inline-flex items-center gap-1 rounded-chip bg-accent-100 px-2 py-1 text-[11px] font-semibold text-accent-700"><i className={STORY_TYPES[m.event_type]?.icon}/>{STORY_TYPES[m.event_type]?.label}</span><button onClick={()=>setConfirmDelete({kind:'moment',id:m.id,photoUrl:m.photo_url})} className="flex h-9 w-9 items-center justify-center text-foreground-300 hover:text-accent-600 cursor-pointer"><i className="ri-delete-bin-line"/></button></div>{m.photo_url&&<img src={m.photo_url} alt={m.title} className="mb-2 max-h-72 w-full rounded-input bg-background-50 object-contain"/>}<h3 className="text-sm font-bold text-foreground-950">{m.title}</h3>{m.description&&<p className="mt-1 whitespace-pre-wrap text-sm leading-6 text-foreground-700">{m.description}</p>}</div>)}
    {day.repentances.map(r=><div key={r.id} className="rounded-input border border-accent-100 bg-accent-50/50 p-4"><div className="mb-2 flex items-center justify-between"><span className="inline-flex items-center gap-1 rounded-chip bg-accent-100 px-2 py-1 text-[11px] font-semibold text-accent-700"><i className="ri-hand-heart-line"/>회개와 기도</span><button onClick={()=>setConfirmDelete({kind:'repentance',id:r.id})} className="flex h-9 w-9 items-center justify-center text-foreground-300 hover:text-accent-600 cursor-pointer"><i className="ri-delete-bin-line"/></button></div><p className="whitespace-pre-wrap text-sm leading-7 text-foreground-700">{r.content}</p>{r.scripture&&<p className="mt-2 font-quote text-xs text-accent-700">{r.scripture}</p>}{r.prayer&&<div className="mt-2 rounded-input border border-accent-100 bg-background-100 p-3"><p className="text-xs font-bold text-accent-700"><i className="ri-hand-heart-line mr-1"/>기도</p><p className="mt-1 whitespace-pre-wrap text-sm leading-6 text-foreground-700">{r.prayer}</p></div>}</div>)}
   </div></motion.article>)}</div></div>}
  </motion.div>
 </div>
 <AnimatePresence>{showComposer&&user&&<DiaryComposer userId={user.id} onClose={()=>setShowComposer(false)} onSaved={()=>{setShowComposer(false);void load()}}/>}{confirmDelete&&<motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="fixed inset-0 z-[60] flex items-center justify-center bg-foreground-950/40 p-4" onClick={()=>setConfirmDelete(null)}><motion.div initial={{opacity:0,scale:.97}} animate={{opacity:1,scale:1}} className="w-full max-w-xs rounded-card bg-background-100 p-6 text-center shadow-card-lg" onClick={e=>e.stopPropagation()}><div className="mx-auto mb-3 flex h-12 w-12 items-center justify-center rounded-chip bg-accent-100 text-accent-600"><i className="ri-delete-bin-line text-xl"/></div><p className="text-base font-bold text-foreground-950">기록을 삭제할까요?</p><p className="mb-5 mt-1 text-xs text-foreground-500">삭제한 기록은 되돌릴 수 없어요.</p><div className="flex gap-2"><button onClick={()=>setConfirmDelete(null)} className="min-h-11 flex-1 rounded-chip border border-background-200 text-sm font-semibold text-foreground-600 cursor-pointer">취소</button><button onClick={()=>void remove()} className="min-h-11 flex-1 rounded-chip bg-accent-500 text-sm font-bold text-background-50 cursor-pointer">삭제</button></div></motion.div></motion.div>}</AnimatePresence>
 </div>;
}
