import "jsr:@supabase/functions-js/edge-runtime.d.ts";

type ChatMessage={role:"system"|"user"|"assistant";content:string};
type ChatOptions={task:string;messages:ChatMessage[];temperature?:number;maxTokens?:number};
type Provider={name:string;key:string;modelEnv:string;model:string;url:string;quality:number};
type LimitRow={provider:string;rpm:number|null;tpm:number|null;rpd:number|null;tpd:number|null;monthly_tokens:number|null;safety_ratio:number|null;enabled:boolean|null};
type UsageRow={provider:string;window_type:string;request_count:number;total_tokens:number;remaining_requests:number|null;remaining_tokens:number|null;observed_limit_requests:number|null;observed_limit_tokens:number|null;reset_at:string|null};
const env=(n:string)=>Deno.env.get(n)||"";
const SB_URL=env("SUPABASE_URL").replace(/\/$/,"");
const SB_KEY=env("SUPABASE_SERVICE_ROLE_KEY");
const PROVIDERS:Provider[]=[
{name:"gemini",key:"GEMINI_API_KEY",modelEnv:"GEMINI_MODEL",model:"gemini-3.6-flash",url:"https://generativelanguage.googleapis.com/v1beta/models",quality:99},
{name:"nvidia",key:"NVIDIA_KEY_FALLBACK",modelEnv:"NVIDIA_MODEL",model:"z-ai/glm-5.2",url:"https://integrate.api.nvidia.com/v1/chat/completions",quality:99},
{name:"deepseek",key:"DEEPSEEK_API_KEY",modelEnv:"DEEPSEEK_MODEL",model:"deepseek-chat-v3-2",url:"https://api.deepseek.com/v1/chat/completions",quality:98},
{name:"groq",key:"GROQ_API_KEY",modelEnv:"GROQ_MODEL",model:"moonshotai/kimi-k2-instruct",url:"https://api.groq.com/openai/v1/chat/completions",quality:97},
{name:"mistral",key:"MISTRAL_API_KEY",modelEnv:"MISTRAL_MODEL",model:"mistral-medium-3-5-128b",url:"https://api.mistral.ai/v1/chat/completions",quality:97},
{name:"sambanova",key:"SAMBANOVA_API_KEY",modelEnv:"SAMBANOVA_MODEL",model:"deepseek-v3-2-preview",url:"https://api.sambanova.ai/v1/chat/completions",quality:97},
{name:"cohere",key:"COHERE_API_KEY",modelEnv:"COHERE_MODEL",model:"command-a-218b",url:"https://api.cohere.com/v2/chat",quality:96},
{name:"openrouter",key:"OPENROUTER_API_KEY",modelEnv:"OPENROUTER_MODEL",model:"nvidia/nemotron-3-ultra-550b-a55b:free",url:"https://openrouter.ai/api/v1/chat/completions",quality:96},
{name:"cerebras",key:"CEREBRAS_API_KEY",modelEnv:"CEREBRAS_MODEL",model:"llama3.1-70b",url:"https://api.cerebras.ai/v1/chat/completions",quality:94},
{name:"huggingface",key:"HUGGINGFACE_API_KEY",modelEnv:"HUGGINGFACE_MODEL",model:"meta-llama/Meta-Llama-3.1-70B-Instruct",url:"https://router.huggingface.co/v1/chat/completions",quality:90},
{name:"github-models",key:"GITHUB_MODELS_API_KEY",modelEnv:"GITHUB_MODELS_MODEL",model:"Mistral-large-2411",url:"https://models.github.ai/inference",quality:94},
{name:"llm7",key:"LLM7_API_KEY",modelEnv:"LLM7_MODEL",model:"deepseek-r1-0528",url:"https://api.llm7.io/v1/chat/completions",quality:96},
{name:"zai",key:"ZAI_API_KEY",modelEnv:"ZAI_MODEL",model:"glm-4.7",url:"https://open.bigmodel.cn/api/paas/v4/chat/completions",quality:95},
{name:"xai",key:"XAI_API_KEY",modelEnv:"XAI_MODEL",model:"grok-4-1-fast",url:"https://api.x.ai/v1/chat/completions",quality:97}
];
const cooldown=new Map<string,number>();
let quotaCache:{until:number;limits:Map<string,LimitRow>;usage:Map<string,UsageRow>}={until:0,limits:new Map(),usage:new Map()};
function keyFor(p:Provider){const direct=env(p.key);if(direct)return direct;if(p.name==="nvidia")for(const[k,v]of Object.entries(Deno.env.toObject()))if(k.startsWith("NVIDIA_KEY_")&&v)return v;return "";}
function configured(p:Provider){return !!keyFor(p);}
function modelFor(p:Provider){return env(p.modelEnv)||p.model;}
function latestUser(ms:ChatMessage[]){return [...ms].reverse().find(m=>m.role==="user")?.content?.trim()||"";}
function questionType(q:string,task:string){const t=`${task} ${q}`.toLowerCase();if(/불안|떨|걱정|힘들|속상|우울|스트레스|고민|두렵|무서|막막|상담/.test(q))return"counseling";if(/아이디어|추천|기획|행사|프로그램|계획|방법|만들|작성|정리|문구|제안/.test(t))return"creation";if(/\?|뭐야|무엇|어떻게|왜|언제|어디|가능|알려줘|설명|의미/.test(q))return"information";return"general";}
function buildPrompt(o:ChatOptions){const q=latestUser(o.messages),type=questionType(q,o.task);const old=o.messages.filter(m=>m.role==="system").map(m=>m.content.trim()).filter(Boolean).join("\n\n");return [old,"당신은 한국 학생회 웹사이트의 고품질 AI입니다.",`TASK: ${o.task||"general"}`,`QUESTION_TYPE: ${type}`,`LATEST_USER_QUESTION:\n${q}`,"","반드시 가장 최근 사용자 질문에 직접 답하세요.","이전 메시지는 현재 질문을 이해하는 데 필요할 때만 참고하세요.","질문의 구체적인 대상·상황·시간·목적·제약을 답변에 반영하세요.","키워드만 끼워 넣은 일반론, 템플릿 문장, 뜬금없는 말씀이나 사례를 사용하지 마세요.","고민/상담은 공감 뒤에 현실적인 다음 행동이나 실제로 사용할 말까지 제시하세요.","정보 질문은 핵심 답을 첫 문장부터 제시하고 불확실한 내용은 지어내지 마세요.","추천/기획은 실행 가능한 선택지와 장단점, 우선순위를 제시하세요.","성경/신앙 질문은 문맥에 맞는 본문만 연결하고 본문에 없는 내용을 사실처럼 단정하지 마세요.","사용자가 요청한 숫자·형식·날짜·이름은 정확히 유지하세요.","첫 1~2문장은 질문에 대한 직접적인 답 또는 판단으로 시작하세요.","출력 전 내부적으로 질문과 답변이 정확히 일치하는지 점검하고 필요하면 다시 작성하세요."].filter(Boolean).join("\n");}
function prepared(o:ChatOptions){return[{role:"system" as const,content:buildPrompt(o)},...o.messages.filter(m=>m.role!=="system")];}
function maxTokens(o:ChatOptions){const n=Number(o.maxTokens);return Math.min(Math.max(Number.isFinite(n)&&n>0?n:1800,900),3600);}
async function request(p:Provider,o:ChatOptions,signal:AbortSignal){const messages=prepared(o),temperature=Math.min(o.temperature??0.32,0.45),max_tokens=maxTokens(o);if(p.name==="gemini"){const system=messages[0].content;const contents=messages.slice(1).map(m=>({role:m.role==="assistant"?"model":"user",parts:[{text:m.content}]}));return fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(modelFor(p))}:generateContent?key=${encodeURIComponent(keyFor(p))}`,{method:"POST",signal,headers:{"Content-Type":"application/json"},body:JSON.stringify({systemInstruction:{parts:[{text:system}]},contents,generationConfig:{temperature,maxOutputTokens:max_tokens}})});}if(p.name==="cohere"){const rest=messages.slice(1);return fetch(p.url,{method:"POST",signal,headers:{"Content-Type":"application/json",Authorization:`Bearer ${keyFor(p)}`},body:JSON.stringify({model:modelFor(p),preamble:messages[0].content,messages:rest.map(m=>({role:m.role==="assistant"?"CHATBOT":"USER",message:m.content})),temperature,max_tokens})});}return fetch(p.url,{method:"POST",signal,headers:{"Content-Type":"application/json",Authorization:`Bearer ${keyFor(p)}`},body:JSON.stringify({model:modelFor(p),messages,temperature,max_tokens})});}
function extract(name:string,d:any){if(name==="gemini")return d?.candidates?.[0]?.content?.parts?.map((x:any)=>x?.text||"").join("")||"";if(name==="cohere")return d?.message?.content?.map((x:any)=>x?.text||"").join("")||"";return d?.choices?.[0]?.message?.content||"";}
function tokenUsage(name:string,d:any){if(name==="gemini")return{input:Number(d?.usageMetadata?.promptTokenCount)||0,output:Number(d?.usageMetadata?.candidatesTokenCount)||0};if(name==="cohere")return{input:Number(d?.usage?.tokens?.input_tokens)||0,output:Number(d?.usage?.tokens?.output_tokens)||0};return{input:Number(d?.usage?.prompt_tokens)||Number(d?.usage?.input_tokens)||0,output:Number(d?.usage?.completion_tokens)||Number(d?.usage?.output_tokens)||0};}
function headerNum(r:Response,n:string[]){for(const k of n){const v=Number(r.headers.get(k));if(Number.isFinite(v))return v;}return null;}
function resetHeader(r:Response){for(const k of ["x-ratelimit-reset-requests","x-ratelimit-reset-tokens","x-ratelimit-reset","retry-after"]){const raw=r.headers.get(k);const v=Number(raw);if(!raw||!Number.isFinite(v))continue;if(v>1e12)return new Date(v).toISOString();if(v>1e9)return new Date(v*1000).toISOString();return new Date(Date.now()+Math.max(1,v)*1000).toISOString();}return null;}
function windowStarts(){const n=new Date(),m=new Date(n),d=new Date(n),mo=new Date(n);m.setSeconds(0,0);d.setUTCHours(0,0,0,0);mo.setUTCDate(1);mo.setUTCHours(0,0,0,0);return{minute:m.toISOString(),day:d.toISOString(),month:mo.toISOString()};}
async function sb(path:string,init:RequestInit={}){if(!SB_URL||!SB_KEY)return null;return fetch(`${SB_URL}/rest/v1/${path}`,{...init,headers:{apikey:SB_KEY,Authorization:`Bearer ${SB_KEY}`,"Content-Type":"application/json",...(init.headers||{})}});}
async function loadQuota(){if(quotaCache.until>Date.now())return quotaCache;const next={until:Date.now()+3000,limits:new Map<string,LimitRow>(),usage:new Map<string,UsageRow>()};try{const[a,b]=await Promise.all([sb("ai_provider_limits?select=*"),sb("ai_provider_usage?select=*&order=updated_at.desc&limit=2000")]);if(a?.ok)for(const x of await a.json() as LimitRow[])next.limits.set(x.provider,x);if(b?.ok)for(const x of await b.json() as UsageRow[]){const k=`${x.provider}:${x.window_type}`;if(!next.usage.has(k))next.usage.set(k,x);}}catch{}quotaCache=next;return next;}
function quotaAllowed(p:Provider,q:any){const l=q.limits.get(p.name) as LimitRow|undefined;if(l?.enabled===false)return false;const safety=Math.min(Math.max(Number(l?.safety_ratio??0.8),0.5),0.95);for(const k of ["minute","day","month"]){const u=q.usage.get(`${p.name}:${k}`) as UsageRow|undefined;if(!u)continue;if(u.reset_at&&new Date(u.reset_at).getTime()<=Date.now())continue;if(u.remaining_requests!=null&&u.observed_limit_requests!=null&&u.observed_limit_requests>0&&u.remaining_requests<=u.observed_limit_requests*(1-safety))return false;if(u.remaining_tokens!=null&&u.observed_limit_tokens!=null&&u.observed_limit_tokens>0&&u.remaining_tokens<=u.observed_limit_tokens*(1-safety))return false;if(k==="minute"&&l?.rpm!=null&&u.request_count>=l.rpm*safety)return false;if(k==="minute"&&l?.tpm!=null&&u.total_tokens>=l.tpm*safety)return false;if(k==="day"&&l?.rpd!=null&&u.request_count>=l.rpd*safety)return false;if(k==="day"&&l?.tpd!=null&&u.total_tokens>=l.tpd*safety)return false;if(k==="month"&&l?.monthly_tokens!=null&&u.total_tokens>=l.monthly_tokens*safety)return false;}return true;}
async function record(p:string,input:number,output:number,error:boolean,rate:boolean,r:Response|null){const h=r?{rr:headerNum(r,["x-ratelimit-remaining-requests","x-ratelimit-remaining"]),rt:headerNum(r,["x-ratelimit-remaining-tokens"]),lr:headerNum(r,["x-ratelimit-limit-requests","x-ratelimit-limit"]),lt:headerNum(r,["x-ratelimit-limit-tokens"]),reset:resetHeader(r)}:{rr:null,rt:null,lr:null,lt:null,reset:null};for(const[k,s]of Object.entries(windowStarts())){try{await sb("rpc/ai_provider_usage_touch",{method:"POST",body:JSON.stringify({p_provider:p,p_window_type:k,p_window_started_at:s,p_input_tokens:input,p_output_tokens:output,p_error:error,p_rate_limited:rate,p_reset_at:h.reset,p_remaining_requests:h.rr,p_remaining_tokens:h.rt,p_observed_limit_requests:h.lr,p_observed_limit_tokens:h.lt})});}catch{}}}
function relevant(answer:string,question:string,task:string){const s=answer.trim().toLowerCase(),type=questionType(question,task);if(s.length<80)return false;if(/^(좋은 질문입니다|무엇을 도와드릴까요|도움이 되길 바랍니다|궁금한 점이 있다면)[.!]?$/i.test(s))return false;if(/^(죄송합니다|잘 모르겠습니다|확인할 수 없습니다)[.!]?$/i.test(s))return false;const tokens=(question.toLowerCase().match(/[가-힣]{2,}|[a-z][a-z0-9_-]{2,}/g)||[]).filter(x=>!['그리고','그런','이런','저런','정말','같아요','있어요','합니다','하세요','대한','위해','통해','경우','조금','사실'].includes(x)).slice(0,14);const hits=tokens.filter(t=>s.includes(t)).length;if(question.length>=18&&hits===0)return false;if(type==="counseling"&&s.length<140)return false;if(type==="creation"&&s.length<160)return false;if(type==="creation"&&s.split(/\n+/).filter(Boolean).length<3)return false;const generic=[/힘들 수 있습니다/,/도움이 될 거예요/,/잘 준비하면 됩니다/,/긍정적으로 생각하세요/,/차분하게 생각해보세요/];if(generic.filter(r=>r.test(s)).length>=3&&hits<2)return false;return true;}
function ordered(ps:Provider[],type:string){const preferred=type==="counseling"?["gemini","deepseek","xai","mistral","cohere","groq","sambanova","openrouter","zai","llm7","github-models","cerebras","nvidia"]:type==="creation"?["gemini","groq","mistral","deepseek","xai","sambanova","cohere","openrouter","nvidia","zai","llm7","github-models","cerebras"]:["gemini","nvidia","deepseek","groq","mistral","sambanova","openrouter","xai","cohere","cerebras","zai","llm7","github-models"];const rank=new Map(preferred.map((x,i)=>[x,i]));return[...ps].sort((a,b)=>{const ar=rank.get(a.name)??999,br=rank.get(b.name)??999;if(ar!==br)return ar-br;return b.quality-a.quality;});}
export async function callQualityAI(o:ChatOptions):Promise<Response>{const quota=await loadQuota();const ps=ordered(PROVIDERS.filter(configured),questionType(latestUser(o.messages),o.task));if(!ps.length)throw new Error("No AI provider configured");const started=Date.now(),failures:string[]=[];let attempts=0;for(const p of ps){if(attempts>=7||Date.now()-started>18000)break;if((cooldown.get(p.name)||0)>Date.now()||!quotaAllowed(p,quota))continue;attempts++;const c=new AbortController();const t=setTimeout(()=>c.abort(),Math.min(5200,Math.max(1800,17500-(Date.now()-started))));let r:Response|null=null;try{r=await request(p,o,c.signal);if(r.ok){const data=await r.json(),answer=extract(p.name,data),u=tokenUsage(p.name,data);if(relevant(answer,latestUser(o.messages),o.task)){await record(p.name,u.input,u.output,false,false,r);return new Response(JSON.stringify({choices:[{message:{content:answer}}]}),{status:200,headers:{"Content-Type":"application/json","Cache-Control":"no-store","X-AI-Provider":p.name,"X-AI-Quality":"strict-v3","X-AI-Quota":"tracked","X-AI-Fallback-Count":String(attempts-1)}});}failures.push(`${p.name}:quality`);await record(p.name,u.input,u.output,true,false,r);cooldown.set(p.name,Date.now()+2500);}else{const rate=r.status===429;failures.push(`${p.name}:${r.status}`);await record(p.name,0,0,true,rate,r);if(rate||r.status>=500)cooldown.set(p.name,Date.now()+30000);}}catch(e){failures.push(`${p.name}:${e instanceof DOMException&&e.name==="AbortError"?"timeout":"network"}`);await record(p.name,0,0,true,false,r);cooldown.set(p.name,Date.now()+5000);}finally{clearTimeout(t);}}throw new Error(`All AI providers failed quality checks: ${failures.join(",")}`);}
