import "jsr:@supabase/functions-js/edge-runtime.d.ts";
type ChatMessage={role:"system"|"user"|"assistant";content:string};
type ChatOptions={task:string;messages:ChatMessage[];temperature?:number;maxTokens?:number};
type Provider={name:string;key:string;modelEnv:string;model:string;url:string;quality:number};
type LimitRow={provider:string;rpm:number|null;tpm:number|null;rpd:number|null;tpd:number|null;monthly_tokens:number|null;safety_ratio:number|null;enabled:boolean|null};
type UsageRow={provider:string;window_type:string;request_count:number;total_tokens:number;remaining_requests:number|null;remaining_tokens:number|null;observed_limit_requests:number|null;observed_limit_tokens:number|null;reset_at:string|null};
const env=(n:string)=>Deno.env.get(n)||"";
const SB_URL=env("SUPABASE_URL").replace(/\/$/,"");
const SB_KEY=env("SUPABASE_SERVICE_ROLE_KEY");
const PROVIDERS:Provider[]=[
{name:"gemini",key:"GEMINI_API_KEY",modelEnv:"GEMINI_MODEL",model:"gemini-3.6-flash",url:"https://generativelanguage.googleapis.com/v1beta/models",quality:100},
{name:"nvidia",key:"NVIDIA_KEY_FALLBACK",modelEnv:"NVIDIA_MODEL",model:"z-ai/glm-5.2",url:"https://integrate.api.nvidia.com/v1/chat/completions",quality:99},
{name:"deepseek",key:"DEEPSEEK_API_KEY",modelEnv:"DEEPSEEK_MODEL",model:"deepseek-chat",url:"https://api.deepseek.com/v1/chat/completions",quality:98},
{name:"openrouter",key:"OPENROUTER_API_KEY",modelEnv:"OPENROUTER_MODEL",model:"nvidia/nemotron-3-ultra-550b-a55b:free",url:"https://openrouter.ai/api/v1/chat/completions",quality:98},
{name:"groq",key:"GROQ_API_KEY",modelEnv:"GROQ_MODEL",model:"openai/gpt-oss-120b",url:"https://api.groq.com/openai/v1/chat/completions",quality:97},
{name:"xai",key:"XAI_API_KEY",modelEnv:"XAI_MODEL",model:"grok-4-1-fast",url:"https://api.x.ai/v1/chat/completions",quality:97},
{name:"mistral",key:"MISTRAL_API_KEY",modelEnv:"MISTRAL_MODEL",model:"mistral-small-latest",url:"https://api.mistral.ai/v1/chat/completions",quality:96},
{name:"cloudflare",key:"CLOUDFLARE_API_TOKEN",modelEnv:"CLOUDFLARE_MODEL",model:"@cf/openai/gpt-oss-120b",url:"",quality:96},
{name:"modelscope",key:"MODELSCOPE_API_KEY",modelEnv:"MODELSCOPE_MODEL",model:"ZhipuAI/GLM-4.7-Flash",url:"https://api-inference.modelscope.cn/v1/chat/completions",quality:96},
{name:"sambanova",key:"SAMBANOVA_API_KEY",modelEnv:"SAMBANOVA_MODEL",model:"Meta-Llama-3.3-70B-Instruct",url:"https://api.sambanova.ai/v1/chat/completions",quality:95},
{name:"cohere",key:"COHERE_API_KEY",modelEnv:"COHERE_MODEL",model:"command-a-03-2025",url:"https://api.cohere.com/v2/chat",quality:94},
{name:"zai",key:"ZAI_API_KEY",modelEnv:"ZAI_MODEL",model:"glm-4.7",url:"https://open.bigmodel.cn/api/paas/v4/chat/completions",quality:94},
{name:"llm7",key:"LLM7_API_KEY",modelEnv:"LLM7_MODEL",model:"deepseek-r1-0528",url:"https://api.llm7.io/v1/chat/completions",quality:93},
{name:"cerebras",key:"CEREBRAS_API_KEY",modelEnv:"CEREBRAS_MODEL",model:"gemma-4-31b",url:"https://api.cerebras.ai/v1/chat/completions",quality:92},
{name:"github-models",key:"GITHUB_MODELS_API_KEY",modelEnv:"GITHUB_MODELS_MODEL",model:"Mistral-large-2411",url:"https://models.github.ai/inference",quality:90},
{name:"huggingface",key:"HUGGINGFACE_API_KEY",modelEnv:"HUGGINGFACE_MODEL",model:"meta-llama/Meta-Llama-3.1-70B-Instruct",url:"https://router.huggingface.co/v1/chat/completions",quality:90},
{name:"together",key:"TOGETHER_API_KEY",modelEnv:"TOGETHER_MODEL",model:"meta-llama/Llama-3.3-70B-Instruct-Turbo",url:"https://api.together.xyz/v1/chat/completions",quality:89}
];
const cooldown=new Map<string,number>();
let quotaCache:{until:number;limits:Map<string,LimitRow>;usage:Map<string,UsageRow>}={until:0,limits:new Map(),usage:new Map()};
const latest=(m:ChatMessage[])=>[...m].reverse().find(x=>x.role==="user")?.content?.trim()||"";
const type=(q:string,t:string)=>{const z=(t+" "+q).toLowerCase();if(/불안|떨|걱정|힘들|속상|우울|스트레스|고민|두렵|무서|막막|상담|위로/.test(q))return"counseling";if(/성경|말씀|예배|기도|신앙|하나님|예수|교회/.test(z))return"faith";if(/학생회|사명자|동아리|월례회|캠페인|공연|출석|보고서/.test(z))return"council";if(/아이디어|추천|기획|행사|프로그램|계획|방법|만들|작성|정리|문구|제안/.test(z))return"creation";if(/\?|뭐야|무엇|어떻게|왜|언제|어디|가능|알려줘|설명|의미/.test(q))return"information";return"general"};
const keyFor=(p:Provider)=>env(p.key)||(p.name==="nvidia"?Object.entries(Deno.env.toObject()).find(([k,v])=>k.startsWith("NVIDIA_KEY_")&&v)?.[1]||"":"");
const configured=(p:Provider)=>!!keyFor(p),modelFor=(p:Provider)=>env(p.modelEnv)||p.model;
function system(o:ChatOptions){const q=latest(o.messages),t=type(q,o.task);return [o.messages.filter(m=>m.role==="system").map(m=>m.content.trim()).filter(Boolean).join("\n\n"),"당신은 한국 학생회 웹사이트의 최고 품질 AI입니다.",`작업: ${o.task||"general"}`,`질문 유형: ${t}`,`최신 사용자 질문:\n${q}`,"","가장 최근 질문에 직접 답하세요. 이전 맥락과 충돌하면 최신 질문을 우선하세요.","질문의 실제 상황·대상·시간·목적·제약을 답변에 반영하세요.","질문에 없는 사실을 지어내지 마세요.","뻔한 일반론과 템플릿을 피하고 실제로 쓸 수 있는 방법·예시·순서·문장을 우선하세요.","상담은 공감 후 현실적인 다음 행동까지 제시하세요. 훈계하지 마세요.","학생회 질문은 실제 운영 가능한 우선순위와 실행안을 제시하세요.","신앙/성경은 문맥에 맞는 내용만 사용하고 확인되지 않은 인용은 하지 마세요.","숫자·날짜·이름·요청 형식을 정확히 보존하세요.","답변 첫 1~2문장은 핵심 답 또는 판단으로 바로 시작하세요.","출력 전 질문과 답변이 정확히 일치하는지 내부적으로 점검하세요."].filter(Boolean).join("\n")}
const prepared=(o:ChatOptions)=>[{role:"system" as const,content:system(o)},...o.messages.filter(m=>m.role!=="system")];
const maxTokens=(o:ChatOptions)=>Math.min(Math.max(Number(o.maxTokens)||1800,900),4200);
async function sb(path:string,init:RequestInit={}){if(!SB_URL||!SB_KEY)return null;return fetch(`${SB_URL}/rest/v1/${path}`,{...init,headers:{apikey:SB_KEY,Authorization:`Bearer ${SB_KEY}`,"Content-Type":"application/json",...(init.headers||{})}})}
async function quota(){if(quotaCache.until>Date.now())return quotaCache;const x={until:Date.now()+3000,limits:new Map<string,LimitRow>(),usage:new Map<string,UsageRow>()};try{const[a,b]=await Promise.all([sb("ai_provider_limits?select=*"),sb("ai_provider_usage?select=*&order=updated_at.desc&limit=2000")]);if(a?.ok)for(const v of await a.json() as LimitRow[])x.limits.set(v.provider,v);if(b?.ok)for(const v of await b.json() as UsageRow[]){const k=`${v.provider}:${v.window_type}`;if(!x.usage.has(k))x.usage.set(k,v)}}catch{}quotaCache=x;return x}
function allowed(p:Provider,q:any){const l=q.limits.get(p.name) as LimitRow|undefined;if(l?.enabled===false)return false;const s=Math.min(Math.max(Number(l?.safety_ratio??0.8),0.5),0.9);for(const w of ["minute","day","month"]){const u=q.usage.get(`${p.name}:${w}`) as UsageRow|undefined;if(!u)continue;if(u.reset_at&&new Date(u.reset_at).getTime()<=Date.now())continue;if(u.remaining_requests!=null&&u.observed_limit_requests!=null&&u.remaining_requests<=u.observed_limit_requests*(1-s))return false;if(u.remaining_tokens!=null&&u.observed_limit_tokens!=null&&u.remaining_tokens<=u.observed_limit_tokens*(1-s))return false;if(w==="minute"&&l?.rpm!=null&&u.request_count>=l.rpm*s)return false;if(w==="minute"&&l?.tpm!=null&&u.total_tokens>=l.tpm*s)return false;if(w==="day"&&l?.rpd!=null&&u.request_count>=l.rpd*s)return false;if(w==="day"&&l?.tpd!=null&&u.total_tokens>=l.tpd*s)return false;if(w==="month"&&l?.monthly_tokens!=null&&u.total_tokens>=l.monthly_tokens*s)return false}return true}
async function request(p:Provider,o:ChatOptions,signal:AbortSignal){const messages=prepared(o),temperature=Math.min(Number(o.temperature)||0.3,0.4),max_tokens=maxTokens(o);if(p.name==="gemini"){const systemText=messages[0].content,contents=messages.slice(1).map(m=>({role:m.role==="assistant"?"model":"user",parts:[{text:m.content}]}));return fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(modelFor(p))}:generateContent?key=${encodeURIComponent(keyFor(p))}`,{method:"POST",signal,headers:{"Content-Type":"application/json"},body:JSON.stringify({systemInstruction:{parts:[{text:systemText}]},contents,generationConfig:{temperature,maxOutputTokens:max_tokens}})});}if(p.name==="cloudflare"){const id=e("CLOUDFLARE_ACCOUNT_ID");return fetch(`https://api.cloudflare.com/client/v4/accounts/${encodeURIComponent(id)}/ai/v1/chat/completions`,{method:"POST",signal,headers:{"Content-Type":"application/json",Authorization:`Bearer ${keyFor(p)}`},body:JSON.stringify({model:modelFor(p),messages,temperature,max_tokens})})}if(p.name==="cohere"){const rest=messages.slice(1);return fetch(p.url,{method:"POST",signal,headers:{"Content-Type":"application/json",Authorization:`Bearer ${keyFor(p)}`},body:JSON.stringify({model:modelFor(p),preamble:messages[0].content,messages:rest.map(m=>({role:m.role==="assistant"?"CHATBOT":"USER",message:m.content})),temperature,max_tokens})});}return fetch(p.url,{method:"POST",signal,headers:{"Content-Type":"application/json",Authorization:`Bearer ${keyFor(p)}`},body:JSON.stringify({model:modelFor(p),messages,temperature,max_tokens})})}
function extract(p:Provider,d:any){if(p.name==="gemini")return d?.candidates?.[0]?.content?.parts?.map((x:any)=>x?.text||"").join("")||"";if(p.name==="cloudflare")return d?.result?.response||d?.result?.output?.text||"";if(p.name==="cohere")return d?.message?.content?.map((x:any)=>x?.text||"").join("")||"";return d?.choices?.[0]?.message?.content||""}
function tokenUsage(p:Provider,d:any){if(p.name==="gemini")return{in:Number(d?.usageMetadata?.promptTokenCount)||0,out:Number(d?.usageMetadata?.candidatesTokenCount)||0};if(p.name==="cohere")return{in:Number(d?.usage?.tokens?.input_tokens)||0,out:Number(d?.usage?.tokens?.output_tokens)||0};return{in:Number(d?.usage?.prompt_tokens)||Number(d?.usage?.input_tokens)||0,out:Number(d?.usage?.completion_tokens)||Number(d?.usage?.output_tokens)||0}}
function quality(a:string,q:string,t:string){const s=a.trim(),ty=type(q,t);if(s.length<80)return 0;if(/^(좋은 질문입니다|무엇을 도와드릴까요|도움이 되길 바랍니다|죄송합니다|잘 모르겠습니다|확인할 수 없습니다)[.!?]?$/i.test(s))return 0;let score=65;const parts=(q.toLowerCase().match(/[가-힣]{2,}|[a-z][a-z0-9_-]{2,}/g)||[]).filter(x=>!['그리고','그런','이런','정말','같아요','있어요','합니다','하세요','대한','위해','통해','경우','조금','사실'].includes(x)).slice(0,14);const hits=parts.filter(x=>s.toLowerCase().includes(x)).length;if(q.length>=18&&parts.length&&hits===0)return 0;score+=Math.min(20,Math.round(hits/Math.max(1,parts.length)*24));if((ty==='counseling'&&s.length<140)||(ty==='creation'&&s.length<160)||(ty==='council'&&s.length<160))return 0;if(ty==='counseling'&&/다음|해보|방법|문장|오늘|내일/.test(s))score+=10;if((ty==='creation'||ty==='council')&&/우선|순서|담당|기한|체크|먼저|다음/.test(s))score+=10;return Math.min(100,score)}
async function record(p:Provider,u:any,err:boolean,rate:boolean,r:Response|null){const reset=r?.headers.get("x-ratelimit-reset")||r?.headers.get("retry-after")||null;const now=new Date(),minute=new Date(now);minute.setSeconds(0,0);const day=new Date(now);day.setUTCHours(0,0,0,0);const month=new Date(now);month.setUTCDate(1);month.setUTCHours(0,0,0,0);for(const [w,s] of Object.entries({minute:minute.toISOString(),day:day.toISOString(),month:month.toISOString()})){try{await sb("rpc/ai_provider_usage_touch",{method:"POST",body:JSON.stringify({p_provider:p.name,p_window_type:w,p_window_started_at:s,p_input_tokens:u.in,p_output_tokens:u.out,p_error:err,p_rate_limited:rate,p_reset_at:reset})})}catch{}}}
const rank=(t:string)=>t==='counseling'?["gemini","nvidia","deepseek","openrouter","xai","mistral","cloudflare","modelscope","groq","sambanova","cohere","zai","llm7","cerebras","github-models","huggingface","together"]:t==='faith'?["gemini","nvidia","deepseek","openrouter","mistral","modelscope","xai","groq","cloudflare","cohere","zai","sambanova","cerebras","llm7","github-models","huggingface","together"]:t==='council'?["gemini","nvidia","deepseek","openrouter","groq","mistral","cloudflare","modelscope","xai","sambanova","cohere","zai","llm7","cerebras","github-models","huggingface","together"]:t==='creation'?["gemini","nvidia","deepseek","openrouter","groq","mistral","xai","cloudflare","modelscope","sambanova","cohere","zai","llm7","cerebras","github-models","huggingface","together"]:["gemini","nvidia","deepseek","openrouter","groq","xai","mistral","cloudflare","modelscope","sambanova","cohere","zai","llm7","cerebras","github-models","huggingface","together"];
export async function callQualityAI(o:ChatOptions):Promise<Response>{const q=await quota(),question=latest(o.messages),t=type(question,o.task),ps=PROVIDERS.filter(configured),rnk=rank(t);ps.sort((a,b)=>{const ar=rnk.indexOf(a.name),br=rnk.indexOf(b.name);return (ar<0?999:ar)-(br<0?999:br)||b.quality-a.quality});const start=Date.now();let tries=0,best:{a:string;score:number;p:Provider}|null=null,fail:string[]=[];for(const p of ps){if(tries>=7||Date.now()-start>18500)break;if((cooldown.get(p.name)||0)>Date.now()||!allowed(p,q))continue;tries++;const c=new AbortController(),tm=setTimeout(()=>c.abort(),Math.min(5400,Math.max(1800,17500-(Date.now()-start))));let r:Response|null=null;try{r=await request(p,o,c.signal);if(r.ok){const d=await r.json(),a=extract(p,d),u=tokenUsage(p,d),score=quality(a,question,o.task);if(score>0){await record(p,u,false,false,r);if(!best||score>best.score)best={a,score,p};if(score>=92){return new Response(JSON.stringify({choices:[{message:{content:a}}]}),{status:200,headers:{"Content-Type":"application/json","X-AI-Provider":p.name,"X-AI-Quality":String(score),"X-AI-Quota":"tracked","X-AI-Fallback-Count":String(tries-1)}})}}else{fail.push(`${p.name}:quality`);await record(p,u,true,false,r);cooldown.set(p.name,Date.now()+2500)}}else{const rl=r.status===429;fail.push(`${p.name}:${r.status}`);await record(p,{in:0,out:0},true,rl,r);if(rl||r.status>=500)cooldown.set(p.name,Date.now()+30000)}}catch(e){fail.push(`${p.name}:${e instanceof DOMException&&e.name==="AbortError"?"timeout":"network"}`);await record(p,{in:0,out:0},true,false,r);cooldown.set(p.name,Date.now()+5000)}finally{clearTimeout(tm)}}if(best)return new Response(JSON.stringify({choices:[{message:{content:best.a}}]}),{status:200,headers:{"Content-Type":"application/json","Cache-Control":"no-store","X-AI-Provider":best.p.name,"X-AI-Quality":String(best.score),"X-AI-Quota":"tracked","X-AI-Fallback-Count":String(Math.max(0,tries-1))}});throw new Error(`AI providers unavailable: ${fail.join(",")}`)}