import type { RouteObject } from "react-router-dom";
import { lazy, Suspense, type ReactNode } from "react";
const WolvesAndSheep = lazy(() => import("@/pages/wolvesAndSheep/page"));
const GameHub = lazy(() => import("@/pages/gameHub/page"));
const Pharisee = lazy(() => import("@/games/pharisee/page"));
const GalileePhone = lazy(() => import("@/games/galilee-phone/page"));
const NotFound = lazy(() => import("@/pages/NotFound"));
const Home = lazy(() => import("@/pages/home/page"));
const BiblePick = lazy(() => import("@/pages/biblePick/page"));
const BiblePickHistory = lazy(() => import("@/pages/biblePick/history/page"));
const Clubs = lazy(() => import("@/pages/clubs/page"));
const ClubDetail = lazy(() => import("@/pages/clubs/detail/page"));
const ClubCommunity = lazy(() => import("@/pages/clubs/community/page"));
const Notices = lazy(() => import("@/pages/notices/page"));
const NoticeWrite = lazy(() => import("@/pages/notices/write/page"));
const NoticeDetail = lazy(() => import("@/pages/notices/detail/page"));
const NoticeEdit = lazy(() => import("@/pages/notices/edit/page"));
const Schedule = lazy(() => import("@/pages/schedule/page"));
const ScheduleWrite = lazy(() => import("@/pages/schedule/write/page"));
const ScheduleEdit = lazy(() => import("@/pages/schedule/edit/page"));
const Login = lazy(() => import("@/pages/login/page"));
const Setup = lazy(() => import("@/pages/setup/page"));
const Dashboard = lazy(() => import("@/pages/dashboard/page"));
const WeeklyReports = lazy(() => import("@/pages/reports/weekly/page"));
const WeeklyReportWrite = lazy(() => import("@/pages/reports/weekly/write/page"));
const WeeklyReportDetail = lazy(() => import("@/pages/reports/weekly/humanDetail"));
const WeeklyReportEdit = lazy(() => import("@/pages/reports/weekly/edit/page"));
const GrowthReports = lazy(() => import("@/pages/reports/growth/page"));
const GrowthReportWrite = lazy(() => import("@/pages/reports/growth/write/page"));
const GrowthRecordDetail = lazy(() => import("@/pages/reports/growth/humanDetail"));
const GrowthReportEdit = lazy(() => import("@/pages/reports/growth/edit/page"));
const EventReports = lazy(() => import("@/pages/reports/events/page"));
const EventReportWrite = lazy(() => import("@/pages/reports/events/write/page"));
const EventReportDetail = lazy(() => import("@/pages/reports/events/humanDetail"));
const EventReportEdit = lazy(() => import("@/pages/reports/events/edit/page"));
const ReviewPage = lazy(() => import("@/pages/reports/review/workflow"));
const AdminRolesPage = lazy(() => import("@/pages/admin/roles/page"));
const StrategyDashboard = lazy(() => import("@/pages/admin/strategy/page"));
const AdminApprovals = lazy(() => import("@/pages/admin/approvals/page"));
const ResetPassword = lazy(() => import("@/pages/reset-password/page"));
import Layout from "@/components/feature/Layout";
import AuthGuard from "@/components/base/AuthGuard";
const BibleMbti = lazy(() => import("@/pages/bibleMbti/page"));
const BibleQuiz = lazy(() => import("@/pages/bibleQuiz/page"));
const BibleStreak = lazy(() => import("@/pages/bibleStreak/page"));
const BibleByAge = lazy(() => import("@/pages/bibleByAge/page"));
const FaithStorybook = lazy(() => import("@/pages/faithStorybook/page"));
const RepentanceJournal = lazy(() => import("@/pages/repentanceJournal/page"));
const FaithJournal = lazy(() => import("@/pages/faithJournal/page"));
const QandABoard = lazy(() => import("@/pages/qnaBoard/page"));
const MemoryBoard = lazy(() => import("@/pages/memoryBoard/page"));
const SongVoteBoard = lazy(() => import("@/pages/songVote/page"));
const PersonalSchedule = lazy(() => import("@/pages/personalSchedule/page"));
const PrayerPartner = lazy(() => import("@/pages/prayerPartner/page"));
const BibleMarathon = lazy(() => import("@/pages/bibleMarathon/page"));
const YearEndSummary = lazy(() => import("@/pages/yearEndSummary/page"));
const BucketListBoard = lazy(() => import("@/pages/bucketList/page"));
const PrayerRelay = lazy(() => import("@/pages/prayerRelay/page"));
const LeadershipDiary = lazy(() => import("@/pages/leadershipDiary/page"));
const AttendanceDashboard = lazy(() => import("@/pages/dashboard/attendance/page"));
const ToolsPage = lazy(() => import("@/pages/tools/page"));
const AbsenceReasonsPage = lazy(() => import("@/pages/settings/absence-reasons/page"));
const AttendanceLocationPage = lazy(() => import("@/pages/settings/attendance-location/page"));
const ProfilePage = lazy(() => import("@/pages/profile/page"));
const TeacherDashboard = lazy(() => import("@/pages/teacherDashboard/enhancedPage"));
const GanghakNewsList = lazy(() => import("@/pages/ganghakNews/page"));
const GanghakNewsDetail = lazy(() => import("@/pages/ganghakNews/detail/page"));
const GanghakNewsWrite = lazy(() => import("@/pages/ganghakNews/write/page"));
const GanghakNewsEdit = lazy(() => import("@/pages/ganghakNews/edit/page"));
const QuizManagePage = lazy(() => import("@/pages/teacherDashboard/quizManage/page"));
const QuoteManagePage = lazy(() => import("@/pages/teacherDashboard/quoteManage/page"));
const StorageCleanupPage = lazy(() => import("@/pages/admin/storageCleanup/page"));
const MemoryThumbnailsMigrationPage = lazy(() => import("@/pages/admin/memoryThumbnails/page"));
const ClubPhotoThumbnailsMigrationPage = lazy(() => import("@/pages/admin/clubPhotoThumbnails/page"));
const SuggestionsPage = lazy(() => import("@/pages/suggestions/page"));
const VisitationsPage = lazy(() => import("@/pages/visitations/page"));
const VisitationWrite = lazy(() => import("@/pages/visitations/write/page"));
const VisitationDetail = lazy(() => import("@/pages/visitations/detail/page"));
const MeetingsPage = lazy(() => import("@/pages/meetings/page"));
const MeetingWritePage = lazy(() => import("@/pages/meetings/write/page"));
const MeetingDetailPage = lazy(() => import("@/pages/meetings/detail/page"));
const MeetingEditPage = lazy(() => import("@/pages/meetings/edit/page"));
const NotebookCopilotPage = lazy(() => import("@/pages/notebookCopilot/page"));
const MissionsPage = lazy(() => import("@/pages/missions/page"));
const MissionBoardPage = lazy(() => import("@/pages/missions/board/page"));
const MissionLeaderboardPage = lazy(() => import("@/pages/missions/leaderboard/page"));
const MissionWallPage = lazy(() => import("@/pages/missions/wall/page"));
const AttendanceBoard = lazy(() => import("@/pages/attendanceBoard/page"));
const HallOfFame = lazy(() => import("@/pages/hallOfFame/page"));
const SearchPage = lazy(() => import("@/pages/search/page"));
const SermonHighlightPage = lazy(() => import("@/pages/sermonHighlight/page"));

const pageFallback = (label = "로딩 중…") => <div className="min-h-[40vh] flex items-center justify-center p-6 text-sm text-muted-foreground">{label}</div>;
const withSuspense = (element: ReactNode) => <Suspense fallback={pageFallback()}>{element}</Suspense>;
const routes: RouteObject[] = [{ element: <Layout />, children: [
{path:"/search",element:withSuspense(<SearchPage/>)},{path:"/",element:<AuthGuard minRole="member">{withSuspense(<Home/>)}</AuthGuard>},{path:"/tools",element:withSuspense(<ToolsPage/>)},{path:"/bible-pick",element:withSuspense(<BiblePick/>)},{path:"/bible-pick/history",element:withSuspense(<BiblePickHistory/>)},{path:"/bible-mbti",element:withSuspense(<BibleMbti/>)},{path:"/bible-quiz",element:withSuspense(<BibleQuiz/>)},{path:"/games",element:withSuspense(<GameHub/>)},{path:"/wolves-and-sheep",element:withSuspense(<WolvesAndSheep/>)},{path:"/pharisee",element:withSuspense(<Pharisee/>)},{path:"/galilee-phone",element:withSuspense(<GalileePhone/>)},{path:"/bible-streak",element:<AuthGuard minRole="member">{withSuspense(<BibleStreak/>)}</AuthGuard>},{path:"/bible-by-age",element:withSuspense(<BibleByAge/>)},{path:"/prayer-relay",element:withSuspense(<PrayerRelay/>)},{path:"/faith-storybook",element:withSuspense(<FaithStorybook/>)},{path:"/repentance-journal",element:withSuspense(<RepentanceJournal/>)},{path:"/faith-journal",element:withSuspense(<FaithJournal/>)},{path:"/qna-board",element:withSuspense(<QandABoard/>)},{path:"/memory-board",element:withSuspense(<MemoryBoard/>)},{path:"/song-vote",element:withSuspense(<SongVoteBoard/>)},{path:"/personal-schedule",element:withSuspense(<PersonalSchedule/>)},{path:"/prayer-partner",element:withSuspense(<PrayerPartner/>)},{path:"/bible-marathon",element:withSuspense(<BibleMarathon/>)},{path:"/year-end-summary",element:withSuspense(<YearEndSummary/>)},{path:"/bucket-list",element:<AuthGuard minRole="member">{withSuspense(<BucketListBoard/>)}</AuthGuard>},{path:"/clubs",element:withSuspense(<Clubs/>)},{path:"/clubs/:id",element:withSuspense(<ClubDetail/>)},{path:"/clubs/:id/community",element:withSuspense(<ClubCommunity/>)},{path:"/notices",element:withSuspense(<Notices/>)},{path:"/notices/write",element:<AuthGuard minRole="assistant_zone_leader">{withSuspense(<NoticeWrite/>)}</AuthGuard>},{path:"/notices/:id/edit",element:<AuthGuard minRole="assistant_zone_leader">{withSuspense(<NoticeEdit/>)}</AuthGuard>},{path:"/notices/:id",element:withSuspense(<NoticeDetail/>)},{path:"/schedule",element:withSuspense(<Schedule/>)},{path:"/schedule/write",element:<AuthGuard minRole="assistant_zone_leader">{withSuspense(<ScheduleWrite/>)}</AuthGuard>},{path:"/schedule/:id/edit",element:<AuthGuard minRole="assistant_zone_leader">{withSuspense(<ScheduleEdit/>)}</AuthGuard>},{path:"/schedule/:id",element:withSuspense(<Schedule/>)},{path:"/login",element:withSuspense(<Login/>)},{path:"/setup",element:withSuspense(<Setup/>)},{path:"/dashboard",element:<AuthGuard minRole="member">{withSuspense(<Dashboard/>)}</AuthGuard>},{path:"/dashboard/attendance",element:<AuthGuard minRole="member">{withSuspense(<AttendanceDashboard/>)}</AuthGuard>},{path:"/reports/weekly",element:<AuthGuard minRole="assistant_zone_leader">{withSuspense(<WeeklyReports/>)}</AuthGuard>},{path:"/reports/weekly/write",element:<AuthGuard minRole="assistant_zone_leader">{withSuspense(<WeeklyReportWrite/>)}</AuthGuard>},{path:"/reports/weekly/:id",element:<AuthGuard minRole="assistant_zone_leader">{withSuspense(<WeeklyReportDetail/>)}</AuthGuard>},{path:"/reports/weekly/:id/edit",element:<AuthGuard minRole="assistant_zone_leader">{withSuspense(<WeeklyReportEdit/>)}</AuthGuard>},{path:"/reports/growth",element:<AuthGuard minRole="assistant_zone_leader">{withSuspense(<GrowthReports/>)}</AuthGuard>},{path:"/reports/growth/write",element:<AuthGuard minRole="assistant_zone_leader">{withSuspense(<GrowthReportWrite/>)}</AuthGuard>},{path:"/reports/growth/:id",element:<AuthGuard minRole="assistant_zone_leader">{withSuspense(<GrowthRecordDetail/>)}</AuthGuard>},{path:"/reports/growth/:id/edit",element:<AuthGuard minRole="assistant_zone_leader">{withSuspense(<GrowthReportEdit/>)}</AuthGuard>},{path:"/reports/events",element:<AuthGuard minRole="assistant_zone_leader">{withSuspense(<EventReports/>)}</AuthGuard>},{path:"/reports/events/write",element:<AuthGuard minRole="assistant_zone_leader">{withSuspense(<EventReportWrite/>)}</AuthGuard>},{path:"/reports/events/:id",element:<AuthGuard minRole="assistant_zone_leader">{withSuspense(<EventReportDetail/>)}</AuthGuard>},{path:"/reports/events/:id/edit",element:<AuthGuard minRole="assistant_zone_leader">{withSuspense(<EventReportEdit/>)}</AuthGuard>},{path:"/reports/review",element:<AuthGuard minRole="assistant_zone_leader">{withSuspense(<ReviewPage/>)}</AuthGuard>},{path:"/admin/roles",element:<AuthGuard minRole="president">{withSuspense(<AdminRolesPage/>)}</AuthGuard>},{path:"/admin/strategy",element:<AuthGuard minRole="president">{withSuspense(<StrategyDashboard/>)}</AuthGuard>},{path:"/admin/approvals",element:<AuthGuard minRole="president">{withSuspense(<AdminApprovals/>)}</AuthGuard>},{path:"/reset-password",element:withSuspense(<ResetPassword/>)},{path:"/settings/absence-reasons",element:<AuthGuard minRole="chief">{withSuspense(<AbsenceReasonsPage/>)}</AuthGuard>},{path:"/settings/attendance-location",element:<AuthGuard minRole="teacher">{withSuspense(<AttendanceLocationPage/>)}</AuthGuard>},{path:"/profile",element:<AuthGuard minRole="member">{withSuspense(<ProfilePage/>)}</AuthGuard>},{path:"/teacher-dashboard",element:<AuthGuard minRole="teacher">{withSuspense(<TeacherDashboard/>)}</AuthGuard>},{path:"/leadership-diary",element:<AuthGuard minRole="assistant_zone_leader">{withSuspense(<LeadershipDiary/>)}</AuthGuard>},{path:"/gangneung-news",element:withSuspense(<GanghakNewsList/>)},{path:"/ganghak-news",element:withSuspense(<GanghakNewsList/>)},{path:"/ganghak-news/:id",element:withSuspense(<GanghakNewsDetail/>)},{path:"/ganghak-news/write",element:<AuthGuard minRole="teacher">{withSuspense(<GanghakNewsWrite/>)}</AuthGuard>},{path:"/ganghak-news/:id/edit",element:<AuthGuard minRole="teacher">{withSuspense(<GanghakNewsEdit/>)}</AuthGuard>},{path:"/teacher-dashboard/quiz-manage",element:<AuthGuard minRole="teacher">{withSuspense(<QuizManagePage/>)}</AuthGuard>},{path:"/teacher-dashboard/quote-manage",element:<AuthGuard minRole="teacher">{withSuspense(<QuoteManagePage/>)}</AuthGuard>},{path:"/admin/storage-cleanup",element:<AuthGuard minRole="president">{withSuspense(<StorageCleanupPage/>)}</AuthGuard>},{path:"/admin/memory-thumbnails",element:<AuthGuard minRole="president">{withSuspense(<MemoryThumbnailsMigrationPage/>)}</AuthGuard>},{path:"/admin/club-photo-thumbnails",element:<AuthGuard minRole="president">{withSuspense(<ClubPhotoThumbnailsMigrationPage/>)}</AuthGuard>},{path:"/suggestions",element:<AuthGuard minRole="member">{withSuspense(<SuggestionsPage/>)}</AuthGuard>},{path:"/sermon-highlight",element:withSuspense(<SermonHighlightPage/>)},{path:"/visitations",element:<AuthGuard minRole="member">{withSuspense(<VisitationsPage/>)}</AuthGuard>},{path:"/visitations/write",element:<AuthGuard minRole="member">{withSuspense(<VisitationWrite/>)}</AuthGuard>},{path:"/visitations/:id",element:<AuthGuard minRole="member">{withSuspense(<VisitationDetail/>)}</AuthGuard>},{path:"/meetings",element:<AuthGuard minRole="member">{withSuspense(<MeetingsPage/>)}</AuthGuard>},{path:"/meetings/write",element:<AuthGuard minRole="member">{withSuspense(<MeetingWritePage/>)}</AuthGuard>},{path:"/meetings/:id",element:<AuthGuard minRole="member">{withSuspense(<MeetingDetailPage/>)}</AuthGuard>},{path:"/meetings/:id/edit",element:<AuthGuard minRole="member">{withSuspense(<MeetingEditPage/>)}</AuthGuard>},{path:"/notebook",element:<AuthGuard minRole="member">{withSuspense(<NotebookCopilotPage/>)}</AuthGuard>},{path:"/missions",element:<AuthGuard minRole="member">{withSuspense(<MissionsPage/>)}</AuthGuard>},{path:"/missions/board",element:<AuthGuard minRole="member">{withSuspense(<MissionBoardPage/>)}</AuthGuard>},{path:"/missions/leaderboard",element:<AuthGuard minRole="member">{withSuspense(<MissionLeaderboardPage/>)}</AuthGuard>},{path:"/missions/wall",element:<AuthGuard minRole="member">{withSuspense(<MissionWallPage/>)}</AuthGuard>},{path:"/attendance-board",element:<AuthGuard minRole="member">{withSuspense(<AttendanceBoard/>)}</AuthGuard>},{path:"/hall-of-fame",element:<AuthGuard minRole="member">{withSuspense(<HallOfFame/>)}</AuthGuard>},{path:"*",element:withSuspense(<NotFound/>)}] }];
export default routes;