import { createContext, useContext, useEffect, useState, useCallback, useRef, type ReactNode } from 'react';
import { supabase } from '@/lib/supabase';
import type { User } from '@supabase/supabase-js';
import type { UserProfile, UserRole } from '@/types/auth';
import { ROLE_HIERARCHY } from '@/types/auth';
import { hasSimplePin, setSimplePin, verifySimplePin, clearSimplePin, isValidPinFormat, markPinActivity, setPinExplicitLock, isPinUnlockValid, setPinUnlockExpiration, clearPinUnlockSession, getAutoLogoutMinutes } from '@/lib/simplePin';
import { authenticateRegisteredPasskey, isPasskeySupported, signInWithPasskey as signInWithPasskeyLib } from '@/lib/passkey';

interface AuthContextValue { user: User | null; profile: UserProfile | null; loading: boolean; profileError: string | null; profileRetrying: boolean; retryProfile: () => Promise<void>; signIn: (email: string, password: string) => Promise<{ error: string | null; user: User | null }>; signInWithPasskey: () => Promise<{ error: string | null }>; signUp: (email: string, password: string, name: string, role: UserRole, club?: string, birthYear?: number, gender?: string, birthMonth?: number, birthDay?: number, interests?: string, grade?: string) => Promise<{ error: string | null }>; signOut: () => Promise<void>; resetPassword: (email: string) => Promise<{ error: string | null }>; updatePassword: (newPassword: string) => Promise<{ error: string | null }>; updateEmail: (newEmail: string) => Promise<{ error: string | null }>; hasRole: (minRole: UserRole) => boolean; assignedTeacherClub: string | null; secondaryClubs: string[]; pinLocked: boolean; hasPin: boolean; pinSetupNeeded: boolean; dismissPinSetupPrompt: () => void; setupPin: (pin: string) => Promise<{ error: string | null }>; changePin: (currentPin: string, newPin: string) => Promise<{ error: string | null }>; removePin: () => void; unlockWithPin: (pin: string) => Promise<boolean>; unlockWithPasskey: () => Promise<boolean>; lockApp: () => void; }

const AuthContext = createContext<AuthContextValue | undefined>(undefined);
function clearAllAuthStorage() { try { for (let i = localStorage.length - 1; i >= 0; i--) { const k = localStorage.key(i); if (k && k.startsWith('sb-')) localStorage.removeItem(k); } } catch {} }

export function AuthProvider({ children }: { children: ReactNode }) {
  const [user, setUser] = useState<User | null>(null); const [profile, setProfile] = useState<UserProfile | null>(null); const [loading, setLoading] = useState(true); const [profileError, setProfileError] = useState<string | null>(null); const [profileRetrying, setProfileRetrying] = useState(false); const [assignedTeacherClub, setAssignedTeacherClub] = useState<string | null>(null); const [secondaryClubs, setSecondaryClubs] = useState<string[]>([]); const [pinLocked, setPinLocked] = useState(false); const [hasPin, setHasPin] = useState(false); const [pinSetupNeeded, setPinSetupNeeded] = useState(false);
  const sessionRestoredRef = useRef(false); const fetchingForRef = useRef<string | null>(null); const refreshFailureHandledRef = useRef(false); const authEventVersionRef = useRef(0); const profileRetryCountRef = useRef(0); const profileRetryTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null); const MAX_PROFILE_RETRIES = 5; const realtimeSubRef = useRef<ReturnType<typeof supabase.channel> | null>(null);
  const handleSessionDead = useCallback(() => { if (refreshFailureHandledRef.current) return; refreshFailureHandledRef.current = true; fetchingForRef.current = null; clearAllAuthStorage(); supabase.auth.signOut({ scope: 'local' }).catch(() => {}); setUser(null); setProfile(null); setProfileError(null); setLoading(false); setPinLocked(false); setHasPin(false); setPinSetupNeeded(false); try { if (window.REACT_APP_NAVIGATE) window.REACT_APP_NAVIGATE('/login', { replace: true }); } catch {} }, []);
  const fetchProfile = useCallback(async (authUser: User) => { const userId = authUser.id; fetchingForRef.current = userId; setProfileError(null); try { const { data, error } = await supabase.from('user_roles').select('*').eq('user_id', userId).maybeSingle(); if (fetchingForRef.current !== userId) return; if (!error && data) { profileRetryCountRef.current = 0; if (profileRetryTimerRef.current) { clearTimeout(profileRetryTimerRef.current); profileRetryTimerRef.current = null; } const profileData = data as UserProfile; if (profileData.is_expelled) { setProfile(null); setProfileError('퇴출된 계정입니다. 관리자에게 문의하세요.'); await supabase.auth.signOut(); return; } const { data: extraRoles } = await supabase.from('user_role_assignments').select('role').eq('user_id', userId); if (extraRoles && extraRoles.length > 0) profileData.roles = [profileData.role, ...extraRoles.map((r: any) => r.role as UserRole)]; setProfile(profileData); return; } const meta = authUser.user_metadata; if (meta?.name) { const safeRole = (meta.role === 'chief' || meta.role === 'teacher') ? 'member' : (meta.role || 'member'); const { data: newProfile, error: insertError } = await supabase.from('user_roles').insert({ user_id: userId, role: safeRole, name: meta.name, club: meta.club || null, birth_year: meta.birth_year || null, is_active: true }).select('*').maybeSingle(); if (fetchingForRef.current !== userId) return; if (!insertError && newProfile) { setProfile(newProfile as UserProfile); return; } const { data: retryData } = await supabase.from('user_roles').select('*').eq('user_id', userId).maybeSingle(); if (fetchingForRef.current !== userId) return; if (retryData) { setProfile(retryData as UserProfile); return; } } setProfileError('프로필 정보를 불러올 수 없습니다. 관리자에게 문의하거나 다시 시도해주세요.'); } catch (e) { if (fetchingForRef.current !== userId) return; console.error('[Auth] fetchProfile exception:', e); setProfileError('프로필 로딩 중 네트워크 오류가 발생했습니다. 다시 시도해주세요.'); if (profileRetryCountRef.current < MAX_PROFILE_RETRIES) { const delay = Math.min(1000 * Math.pow(2, profileRetryCountRef.current), 30000); profileRetryCountRef.current += 1; profileRetryTimerRef.current = setTimeout(() => { if (fetchingForRef.current === userId) fetchProfile(authUser); }, delay); } else { setProfileError('프로필을 불러올 수 없습니다. 페이지를 새로고침하거나 다시 로그인해주세요.'); } } }, []);
  useEffect(() => { function onUnhandledRejection(event: PromiseRejectionEvent) { const reason = event?.reason; const msg = typeof reason?.message === 'string' ? reason.message : String(reason ?? ''); if (msg.includes('Invalid Refresh Token') || msg.includes('Refresh Token Not Found') || msg.includes('AuthSessionMissingError') || reason?.name === 'AuthApiError') { event.preventDefault(); handleSessionDead(); } } window.addEventListener('unhandledrejection', onUnhandledRejection); return () => window.removeEventListener('unhandledrejection', onUnhandledRejection); }, [handleSessionDead]);
  useEffect(() => { let isMounted = true; const getSessionVersion = authEventVersionRef.current; supabase.auth.getSession().then(({ data: { session }, error }) => { if (!isMounted) return; if (authEventVersionRef.current !== getSessionVersion) { sessionRestoredRef.current = true; return; } sessionRestoredRef.current = true; if (error) { if (error.message.includes('Invalid Refresh Token') || error.message.includes('Refresh Token Not Found')) { handleSessionDead(); return; } clearAllAuthStorage(); setUser(null); setProfile(null); setLoading(false); setPinLocked(false); setHasPin(false); setPinSetupNeeded(false); return; } const currentUser = session?.user ?? null; setUser(currentUser); setLoading(false); if (currentUser) { const deviceHasPin = hasSimplePin(currentUser.id); setHasPin(deviceHasPin); if (deviceHasPin) { const unlockValid = isPinUnlockValid(currentUser.id); setPinLocked(!unlockValid); setPinExplicitLock(currentUser.id, !unlockValid); setPinSetupNeeded(false); } else { setPinLocked(false); setPinSetupNeeded(true); } fetchProfile(currentUser); } else { setProfile(null); setHasPin(false); setPinLocked(false); setPinSetupNeeded(false); } }).catch((err) => { if (!isMounted) return; if (authEventVersionRef.current !== getSessionVersion) { sessionRestoredRef.current = true; return; } console.warn('[Auth] getSession exception:', err); clearAllAuthStorage(); sessionRestoredRef.current = true; setUser(null); setProfile(null); setLoading(false); setPinLocked(false); setHasPin(false); setPinSetupNeeded(false); }); const { data: { subscription } } = supabase.auth.onAuthStateChange((event, session) => { if (!isMounted) return; authEventVersionRef.current += 1; if (event === 'TOKEN_REFRESHED') { const refreshedUser = session?.user ?? null; if (refreshedUser) setUser(refreshedUser); else handleSessionDead(); return; } if (event === 'SIGNED_OUT') { fetchingForRef.current = null; clearAllAuthStorage(); setUser(null); setProfile(null); setProfileError(null); setLoading(false); setPinLocked(false); setHasPin(false); setPinSetupNeeded(false); return; } if (event === 'INITIAL_SESSION' && sessionRestoredRef.current) return; const currentUser = session?.user ?? null; setUser(currentUser); setLoading(false); setProfileError(null); if (currentUser) { setHasPin(hasSimplePin(currentUser.id)); setPinExplicitLock(currentUser.id, false); setPinSetupNeeded(false); markPinActivity(currentUser.id); fetchProfile(currentUser); } else { fetchingForRef.current = null; setProfile(null); setHasPin(false); setPinLocked(false); setPinSetupNeeded(false); } }); return () => { isMounted = false; subscription.unsubscribe(); }; }, [fetchProfile, handleSessionDead]);
  useEffect(() => { if (!user) { if (realtimeSubRef.current) { supabase.removeChannel(realtimeSubRef.current); realtimeSubRef.current = null; } return; } const userId = user.id; const channel = supabase.channel(`profile-realtime-${userId}`).on('postgres_changes', { event: '*', schema: 'public', table: 'user_roles', filter: `user_id=eq.${userId}` }, () => { fetchProfile(user); }).on('postgres_changes', { event: '*', schema: 'public', table: 'user_role_assignments', filter: `user_id=eq.${userId}` }, () => { fetchProfile(user); }).on('postgres_changes', { event: '*', schema: 'public', table: 'user_club_assignments', filter: `user_id=eq.${userId}` }, () => { fetchProfile(user); }).subscribe(); realtimeSubRef.current = channel; return () => { supabase.removeChannel(channel); }; }, [user, fetchProfile]);
  const signIn = useCallback(async (email: string, password: string) => { try { refreshFailureHandledRef.current = false; let { data, error } = await supabase.auth.signInWithPassword({ email, password }); if (error) { const apiUrl = String(import.meta.env.VITE_CLOUDFLARE_API_URL || 'https://gnhweb-api.gemini19840314.workers.dev').trim(); const anonKey = String(import.meta.env.VITE_PUBLIC_SUPABASE_ANON_KEY || '').trim(); if (apiUrl && anonKey) { try { const migrationResponse = await fetch(`${apiUrl}/account-password-migration`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email, password, anonKey }) }); if (migrationResponse.ok) { const retry = await supabase.auth.signInWithPassword({ email, password }); data = retry.data; error = retry.error; } } catch (migrationError) { console.warn('[Auth] Legacy password migration unavailable:', migrationError); } } } if (error) return { error: error.message, user: null }; const signedInUser = data.user ?? null; if (signedInUser) { authEventVersionRef.current += 1; setUser(signedInUser); setLoading(false); setProfileError(null); fetchProfile(signedInUser); } return { error: null, user: signedInUser }; } catch (e: unknown) { const errMsg = e instanceof Error && e.message === 'Failed to fetch' ? '서버 연결이 원활하지 않습니다. 네트워크를 확인하고 다시 시도해주세요.' : '로그인 중 오류가 발생했습니다. 잠시 후 다시 시도해주세요.'; console.error('[Auth] signIn exception:', e); return { error: errMsg, user: null }; } }, [fetchProfile]);
  const signUp = useCallback(async (email: string, password: string, name: string, role: UserRole, club?: string, birthYear?: number, gender?: string, birthMonth?: number, birthDay?: number, interests?: string, grade?: string) => { const { data, error } = await supabase.auth.signUp({ email, password, options: { data: { name, club: club || null, birth_year: birthYear || null, gender: gender || null, birth_month: birthMonth || null, birth_day: birthDay || null, interests: interests || null, grade: grade || null } } }); if (error) return { error: error.message }; if (data.session && data.user) { const { error: roleError } = await supabase.from('user_roles').insert({ user_id: data.user.id, role, name, club: club || null, birth_year: birthYear || null, gender: gender || null, birth_month: birthMonth || null, birth_day: birthDay || null, interests: interests || null, grade: grade || null, is_active: true, approval_status: 'pending' }); if (roleError) return { error: roleError.message }; } return { error: null }; }, []);
  const retryProfile = useCallback(async () => { if (!user) return; setProfileRetrying(true); setProfileError(null); try { await fetchProfile(user); } finally { setProfileRetrying(false); } }, [user, fetchProfile]);
  const signInWithPasskey = useCallback(async () => { if (!isPasskeySupported()) return { error: '이 기기에서 패스키 로그인을 사용할 수 없습니다.' }; const result = await signInWithPasskeyLib(); return { error: result.error?.message ?? null }; }, []);
  const signOut = useCallback(async () => { authEventVersionRef.current += 1; fetchingForRef.current = null; setUser(null); setProfile(null); setProfileError(null); setPinLocked(false); setHasPin(false); setPinSetupNeeded(false); if (user) clearPinUnlockSession(user.id); clearAllAuthStorage(); await supabase.auth.signOut({ scope: 'local' }).catch(() => {}); try { if (window.REACT_APP_NAVIGATE) window.REACT_APP_NAVIGATE('/login', { replace: true }); } catch {} }, []);
  const hasRole = useCallback((minRole: UserRole): boolean => { if (!profile) return false; const allRoles = profile.roles || [profile.role]; return allRoles.some(r => ROLE_HIERARCHY[r] >= ROLE_HIERARCHY[minRole]); }, [profile]);
  useEffect(() => { if (!profile || !user) { setAssignedTeacherClub(null); return; } const isTeacherOrChief = profile.role === 'teacher' || profile.role === 'chief'; if (!isTeacherOrChief) { setAssignedTeacherClub(null); return; } Promise.resolve(supabase.from('club_teachers').select('club').eq('teacher_id', user.id)).then(({ data }) => { if (data && data.length > 0) setAssignedTeacherClub(data[0].club as string); else setAssignedTeacherClub(profile.assigned_teacher_id || null); }).catch(() => setAssignedTeacherClub(profile.assigned_teacher_id || null)); }, [profile, user]);
  useEffect(() => { if (!profile || !user) { setSecondaryClubs([]); return; } Promise.resolve(supabase.from('user_club_assignments').select('club').eq('user_id', user.id)).then(({ data }) => { if (data && data.length > 0) setSecondaryClubs(data.map((r: any) => r.club as string)); else setSecondaryClubs([]); }).catch(() => setSecondaryClubs([])); }, [profile, user]);
  const resetPassword = useCallback(async (email: string) => { try { const basePath = __BASE_PATH__.split('/').filter(Boolean).join('/'); const pathPrefix = basePath ? `/${basePath}` : ''; const redirectTo = `${window.location.origin}${pathPrefix}/reset-password`; const { error } = await supabase.auth.resetPasswordForEmail(email, { redirectTo }); if (error) return { error: error.message }; return { error: null }; } catch { return { error: '비밀번호 재설정 메일 발송 중 오류가 발생했습니다.' }; } }, []);
  const updatePassword = useCallback(async (newPassword: string) => { try { const { error } = await supabase.auth.updateUser({ password: newPassword }); if (error) return { error: error.message }; return { error: null }; } catch { return { error: '비밀번호 변경 중 오류가 발생했습니다.' }; } }, []);
  const updateEmail = useCallback(async (newEmail: string) => { try { const { error } = await supabase.auth.updateUser({ email: newEmail }); if (error) return { error: error.message }; return { error: null }; } catch { return { error: '이메일 변경 중 오류가 발생했습니다.' }; } }, []);
  const setupPin = useCallback(async (pin: string) => { if (!user) return { error: '로그인이 필요합니다.' }; if (!isValidPinFormat(pin)) return { error: '숫자 4~6자리로 설정해주세요.' }; await setSimplePin(user.id, pin); setHasPin(true); setPinExplicitLock(user.id, false); setPinSetupNeeded(false); setPinUnlockExpiration(user.id, Date.now() + getAutoLogoutMinutes(user.id) * 60 * 1000); markPinActivity(user.id); return { error: null }; }, [user]);
  const dismissPinSetupPrompt = useCallback(() => { setPinSetupNeeded(false); }, []);
  const changePin = useCallback(async (currentPin: string, newPin: string) => { if (!user) return { error: '로그인이 필요합니다.' }; const ok = await verifySimplePin(user.id, currentPin); if (!ok) return { error: '현재 간편 비밀번호가 일치하지 않습니다.' }; if (!isValidPinFormat(newPin)) return { error: '숫자 4~6자리로 설정해주세요.' }; await setSimplePin(user.id, newPin); return { error: null }; }, [user]);
  const removePin = useCallback(() => { if (!user) return; clearSimplePin(user.id); setHasPin(false); }, [user]);
  const unlockWithPin = useCallback(async (pin: string) => { if (!user) return false; const ok = await verifySimplePin(user.id, pin); if (ok) { setPinLocked(false); setPinExplicitLock(user.id, false); setPinUnlockExpiration(user.id, Date.now() + getAutoLogoutMinutes(user.id) * 60 * 1000); markPinActivity(user.id); } return ok; }, [user]);
  const unlockWithPasskey = useCallback(async () => { if (!user || !isPasskeySupported()) return false; const result = await authenticateRegisteredPasskey(); if (!result.error) { setPinLocked(false); setPinExplicitLock(user.id, false); setPinUnlockExpiration(user.id, Date.now() + getAutoLogoutMinutes(user.id) * 60 * 1000); markPinActivity(user.id); return true; } console.warn('[Auth] Passkey unlock failed:', result.error); return false; }, [user]);
  const lockApp = useCallback(() => { if (user && hasSimplePin(user.id)) { setPinLocked(true); clearPinUnlockSession(user.id); setPinExplicitLock(user.id, true); } }, [user]);
  return <AuthContext.Provider value={{ user, profile, loading, profileError, profileRetrying, retryProfile, signIn, signInWithPasskey, signUp, signOut, resetPassword, updatePassword, updateEmail, hasRole, assignedTeacherClub, secondaryClubs, pinLocked, hasPin, pinSetupNeeded, dismissPinSetupPrompt, setupPin, changePin, removePin, unlockWithPin, unlockWithPasskey, lockApp }}>{children}</AuthContext.Provider>;
}
export function useAuth() { const ctx = useContext(AuthContext); if (!ctx) throw new Error('useAuth must be used within AuthProvider'); return ctx; }