import "jsr:@supabase/functions-js/edge-runtime.d.ts";

type Mode='pick'|'sleep'|'prayer';
type Verse={ref:string;text:string;emotion:string;keywords:string[]};
const verses:Verse[]=[
 {ref:'시편 56:3-4',text:'내가 두려워하는 날에는 내가 주를 의지하리이다. 내가 하나님을 의지하고 그 말씀을 찬송하며 두려워하지 아니하리니',emotion:'불안',keywords:['불안','걱정','두려','무서','떨','긴장','시험','면접','발표','실수']},
 {ref:'빌립보서 4:6-7',text:'아무 것도 염려하지 말고 다만 모든 일에 기도와 간구로 너희 구할 것을 감사함으로 하나님께 아뢰라',emotion:'걱정',keywords:['걱정','염려','불안','시험','성적','미래','진로','결과','부담']},
 {ref:'마태복음 11:28-29',text:'수고하고 무거운 짐 진 자들아 다 내게로 오라 내가 너희를 쉬게 하리라',emotion:'지침',keywords:['지쳐','지침','힘들','피곤','번아웃','무거','압박','스트레스','쉬고','휴식']},
 {ref:'시편 42:11',text:'너는 하나님께 소망을 두라 나는 그가 나타나 도우심으로 말미암아 내 하나님을 여전히 찬송하리로다',emotion:'슬픔',keywords:['슬프','외롭','외로','눈물','우울','허무','상실','친구','관계','이별']},
 {ref:'여호수아 1:9',text:'강하고 담대하라 두려워하지 말며 놀라지 말라 네 하나님 여호와가 너와 함께 하느니라',emotion:'두려움',keywords:['두려','무서','겁','새로운','도전','처음','전학','경기','대회','발표']},
 {ref:'시편 16:11',text:'주께서 생명의 길을 내게 보이시리니 주의 앞에는 충만한 기쁨이 있고',emotion:'기쁨',keywords:['기쁘','행복','좋아','감사','성공','합격','친구','좋은일','기대']},
 {ref:'시편 107:1',text:'여호와께 감사하라 그는 선하시며 그의 인자하심이 영원함이로다',emotion:'감사',keywords:['감사','고마','은혜','도움','축복','합격','회복','좋은일']},
 {ref:'야고보서 1:5',text:'너희 중에 누구든지 지혜가 부족하거든 모든 사람에게 후히 주시고 꾸짖지 아니하시는 하나님께 구하라',emotion:'혼란',keywords:['모르겠','혼란','결정','선택','진로','공부','방법','어떻게','지혜','판단']},
 {ref:'요한일서 1:9',text:'만일 우리가 우리 죄를 자백하면 그는 미쁘시고 의로우사 우리 죄를 사하시며',emotion:'후회',keywords:['후회','미안','죄','잘못','실수','사과','회개','관계']},
 {ref:'이사야 41:10',text:'두려워하지 말라 내가 너와 함께 함이라 놀라지 말라 나는 네 하나님이 됨이라',emotion:'두려움',keywords:['두려','혼자','막막','무서','불안','외로','앞날','미래']},
];
const headers={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Content-Type':'application/json','Cache-Control':'no-store'};
function json(v:unknown,status=200){return new Response(JSON.stringify(v),{status,headers})}
function scoreVerse(text:string,verse:Verse){const lower=text.toLowerCase();let score=0;for(const keyword of verse.keywords){if(lower.includes(keyword.toLowerCase()))score+=3;}if(lower.includes(verse.emotion))score+=5;return score;}
function chooseVerse(text:string):Verse{const scored=verses.map((v,index)=>({v,score:scoreVerse(text,v),index})).sort((a,b)=>b.score-a.score||a.index-b.index);const top=scored.filter(item=>item.score===scored[0].score);return top[0].v;}
function fallback(text:string,verse:Verse){return {verse:verse.text,reference:verse.ref,recommendation:`네가 적어준 “${text.slice(0,110)}”이라는 마음을 보면, 지금은 ${verse.emotion}을 지나가고 있는 것 같아요. 이 말씀은 그 마음을 억지로 없애라고 하기보다 하나님께 그대로 가져가 보라고 권합니다.`,practice:`오늘은 ${verse.emotion}이 올라오는 순간 한 번 멈추고, “하나님, 지금 제 마음을 아십니다”라고 짧게 기도한 뒤 내가 할 수 있는 가장 작은 한 가지를 해보세요.`,prayers:[`하나님, ${text.slice(0,80)}. 제 마음을 아시는 주님께 이 마음을 맡깁니다.`,`${verse.emotion} 가운데서도 제가 혼자가 아니라는 것을 기억하게 해주세요.`],analyzedEmotions:[verse.emotion],primaryEmotion:verse.emotion};}
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers});try{const body=await req.json();const text=String(body?.userText||'').trim();if(!text)return json({error:'내용을 입력해주세요.'},400);const verse=chooseVerse(text);const base=fallback(text,verse);try{const auth=req.headers.get('Authorization')||'';if(auth){const r=await fetch(`${Deno.env.get('SUPABASE_URL')}/functions/v1/ai-gateway`,{method:'POST',headers:{Authorization:auth,'Content-Type':'application/json'},body:JSON.stringify({task:'bible-pick',messages:[{role:'system',content:'너는 청소년을 위한 성경 묵상 도우미다. 사용자가 실제로 적은 상황과 감정을 정확히 읽고, 그 상황에 실제로 도움이 될 한 가지 성경 말씀만 추천한다. 사용자가 말하지 않은 사실을 추측하거나 만들어내지 않는다. 먼저 사용자의 감정을 짧게 인정하고, 추천 말씀이 왜 지금 상황과 연결되는지 구체적으로 설명한다. 훈계하거나 정답을 단정하지 않는다. 오늘 바로 할 수 있는 작고 현실적인 실천 1가지를 제안하고, 자연스러운 짧은 기도 1~2개를 작성한다. 성경 구절 원문은 제공된 추천 구절을 그대로 사용한다. 반드시 JSON 하나만 반환한다. 형식: {"recommendation":"3~4문장","practice":"1~2문장","prayers":["기도1","기도2"]}'},{role:'user',content:`사용자가 적은 상황:\n${text}\n\n선정된 말씀:\n${verse.ref}\n${verse.text}\n\n이 말씀을 위 내용에 자연스럽게 연결해줘.`}],temperature:.1,max_tokens:700})});if(r.ok){const d=await r.json();const raw=String(d?.choices?.[0]?.message?.content||'').replace(/```json/gi,'').replace(/```/g,'').trim();const a=raw.indexOf('{'),b=raw.lastIndexOf('}');if(a>=0&&b>a){const parsed=JSON.parse(raw.slice(a,b+1));if(typeof parsed.recommendation==='string'&&typeof parsed.practice==='string'&&Array.isArray(parsed.prayers)&&parsed.prayers.length>=1)return json({...base,recommendation:parsed.recommendation,practice:parsed.practice,prayers:parsed.prayers.slice(0,2)});}}}}catch{}return json(base)}catch(e){console.error('[bible-pick-v2]',e);return json({error:'말씀을 준비하는 중 오류가 발생했습니다. 잠시 후 다시 시도해주세요.'},503)}});
