import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { logNvidiaUsage } from "../_shared/logNvidiaUsage.ts";
const CORS_HEADERS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Content-Type":"application/json"};
const STRUCTURES=["경쟁형","협동형","미션형","체험형","랜덤매칭형","퀘스트형","투어형","콘텐츠형","제작형","봉사형"];
const FALLBACK_IDEAS=["팀 대항 전략 리그 — 4~6명 팀이 성경 상식, 협동 퍼즐, 제한시간 미션을 순서대로 해결하고 누적 점수로 우승팀을 정한다. 난이도: 중 / 준비물: 문제지, 퍼즐, 타이머","교회 공간 탐험 퀘스트 — 예배실·로비·복도 등 지정 구역을 돌며 성경 단서와 공동체 미션을 해결해 마지막 암호를 완성한다. 난이도: 중 / 준비물: 단서 카드, 봉투, 안내표","랜덤 기도 파트너 릴레이 — 매 라운드 짝을 새로 뽑고 5분 대화 후 한 가지 기도제목을 나누며 마지막에는 서로를 위한 짧은 기도로 마무리한다. 난이도: 하 / 준비물: 추첨도구, 카드","성경 장면 체험 스튜디오 — 팀마다 다른 성경 장면을 배정해 소품·포즈·짧은 대사로 3분 장면을 만들고 서로의 해석을 소개한다. 난이도: 중 / 준비물: 소품, 장면카드, 촬영기기","학생 제작 60초 콘텐츠 데이 — 팀이 행사 주제에서 하나의 메시지를 골라 60초 영상·포스터·밈 중 하나를 직접 제작하고 상영회에서 발표한다. 난이도: 중 / 준비물: 스마트폰, 편집도구, 화면","교회 미니 투어 미션 — 새친구와 기존 학생이 섞인 조를 만들어 교회 공간의 의미와 사역을 소개하는 스탬프 미션을 수행한다. 난이도: 하 / 준비물: 지도, 스탬프, 미션지","감사 나눔 마켓 — 학생들이 감사한 사람에게 줄 작은 메시지나 쿠폰을 직접 만들고 행사 중 서로 교환한 뒤 실제 섬김 한 가지를 약속한다. 난이도: 하 / 준비물: 카드, 펜, 꾸러미"];
function clean(v:unknown,max:number){return typeof v==="string"?v.trim().slice(0,max):""}
function normalize(v:string){return v.toLowerCase().replace(/[^가-힣a-z0-9\s]/g," ").replace(/\s+/g," ").trim()}
function tokenSet(v:string){const stop=new Set(["행사","학생","참여","진행","팀","친구","활동","프로그램","준비","교회"]);return new Set(normalize(v).split(" ").filter(x=>x.length>=2&&!stop.has(x)))}
function similarity(a:string,b:string){const A=tokenSet(a),B=tokenSet(b);if(!A.size||!B.size)return 0;const i=[...A].filter(x=>B.has(x)).length;return i/new Set([...A,...B]).size}
function structureOf(text:string){const t=normalize(text);if(/점수|우승|대항|경쟁/.test(t))return "경쟁형";if(/협동|함께.*해결|공동/.test(t))return "협동형";if(/체험|역할극|장면/.test(t))return "체험형";if(/추첨|랜덤|짝/.test(t))return "랜덤매칭형";if(/투어|공간|스탬프/.test(t))return "투어형";if(/영상|포스터|콘텐츠|제작/.test(t))return "제작형";if(/나눔|봉사|섬김|기부/.test(t))return "봉사형";if(/단서|암호|미션|퀘스트/.test(t))return "퀘스트형";return "참여형"}
function selectDiverse(candidates:string[],count:number){const pool=[...new Set(candidates.map(x=>x.trim()).filter(Boolean))],chosen:string[]=[],structures=new Set<string>();while(chosen.length<count&&pool.length){let best=-Infinity,idx=0;for(let i=0;i<pool.length;i++){const c=pool[i],s=structureOf(c),dup=structures.has(s),sim=chosen.length?Math.max(...chosen.map(x=>similarity(c,x))):0;const score=(dup?-4:4)-sim*8;if(score>best){best=score;idx=i}}const pick=pool.splice(idx,1)[0];chosen.push(pick);structures.add(structureOf(pick))}return chosen.slice(0,count)}
function parse(raw:string){try{const x=JSON.parse(raw.replace(/```json\s*/gi,"").replace(/```/g,"").trim()) as {ideas?:unknown[]};return Array.isArray(x.ideas)?x.ideas.filter((v):v is string=>typeof v==="string").map(v=>v.trim()).filter(Boolean):[]}catch{return []}}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:CORS_HEADERS});try{const body=await req.json(),topic=clean(body?.topic,700),audience=clean(body?.audience,200),budget=clean(body?.budget,120);if(!topic||!audience||!budget)return new Response(JSON.stringify({error:"주제, 대상, 예산을 모두 입력해주세요."}),{status:400,headers:CORS_HEADERS});const apiKey=Deno.env.get("NVIDIA_KEY_EVENTS");if(!apiKey)return new Response(JSON.stringify({title:"행사 아이디어",ideas:FALLBACK_IDEAS,bibleRef:"베드로전서 4:10"}),{headers:CORS_HEADERS});const candidateCount=12;const systemPrompt=`너는 교회 청소년부 학생회 행사를 실제로 기획·운영한 전문가다. 최종 7개가 서로 '실제로 다른 행사'가 되도록 후보를 만든다.\n\n[중복 금지]\n- ${candidateCount}개 후보를 만든다. 제목이나 단어만 바꾼 같은 행사는 중복이다.\n- 가능한 실행 구조: ${STRUCTURES.join(", ")}. 같은 구조는 최대 1~2개만 사용한다.\n- 구조가 다르다는 것은 참가자의 행동, 진행 순서, 공간 사용, 경쟁/협동 방식, 결과물, 역할 중 최소 3가지가 달라지는 것이다.\n- '팀 게임', '팀 미션', '팀 챌린지'처럼 사실상 같은 진행은 서로 다른 아이디어로 세지 않는다.\n- 주제·대상·예산/제약을 반드시 지키고 실제 학생회가 준비할 수 있는 수준으로 작성한다.\n- 추상적인 '재미있는 게임'이 아니라 무엇을 언제 어떻게 하는지 구체적으로 쓴다.\n- 각 후보에는 제목, 핵심 진행, 예상 인원, 비용, 준비물, 난이도를 포함한다.\nJSON만 반환: {"ideas":["후보1",...,"후보${candidateCount}"]}`;const userPrompt=`행사 목적/주제: ${topic}\n대상: ${audience}\n예산/제약: ${budget}\n\n서로 핵심 실행 구조가 겹치지 않는 후보 ${candidateCount}개를 만들어라.`;const response=await fetch("https://integrate.api.nvidia.com/v1/chat/completions",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${apiKey}`},body:JSON.stringify({model:"google/gemma-4-31b-it",messages:[{role:"system",content:systemPrompt},{role:"user",content:userPrompt}],temperature:1.05,max_tokens:5000})});logNvidiaUsage("nim-event-ideas","KEY_EVENTS",response).catch(()=>{});if(!response.ok)return new Response(JSON.stringify({title:"행사 아이디어",ideas:FALLBACK_IDEAS,bibleRef:"베드로전서 4:10"}),{headers:CORS_HEADERS});const result=await response.json();const selected=selectDiverse(parse(result?.choices?.[0]?.message?.content||""),7);const finalIdeas=[...selected];for(const fallback of FALLBACK_IDEAS){if(finalIdeas.length>=7)break;if(finalIdeas.every(x=>similarity(x,fallback)<0.32))finalIdeas.push(fallback)}while(finalIdeas.length<7)finalIdeas.push(FALLBACK_IDEAS[finalIdeas.length%FALLBACK_IDEAS.length]);return new Response(JSON.stringify({title:clean(topic,20)||"행사 아이디어",ideas:finalIdeas.slice(0,7),bibleRef:"베드로전서 4:10"}),{headers:CORS_HEADERS})}catch(error){console.error("[nim-event-ideas]",error);return new Response(JSON.stringify({error:"행사 아이디어를 생성하는 중 오류가 발생했습니다."}),{status:500,headers:CORS_HEADERS})}});
