const CORS_HEADERS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};
const NO_CACHE_HEADERS = { 'Cache-Control': 'no-store, no-cache, must-revalidate, proxy-revalidate', 'Pragma': 'no-cache', 'Expires': '0' };
const CLUB_LABEL_MAP: Record<string, string> = { saeullim:'새울림', cheonjipoong:'천지풍', cheonjihu:'천지후', munhwabu:'문화부', cheonhwarae_cheongmyeong:'천화래와 청명' };
interface ChampionRow { year:number; month:number; category:'quiz'|'marathon'; club_key:string; club_label:string; value:number; extra:Record<string,unknown>|null; }
const DATA_API_URL = 'https://ep-empty-surf-az87wypd.apirest.c-3.ap-southeast-1.aws.neon.tech/neondb/rest/v1';
type Env = Record<string, string | undefined>;
async function neonRequest<T>(env:Env,path:string,init:RequestInit={},authorization?:string):Promise<T>{const headers=new Headers(init.headers);headers.set('Accept','application/json');if(authorization)headers.set('Authorization',authorization);if(init.body&&!headers.has('Content-Type'))headers.set('Content-Type','application/json');const response=await fetch(`${env.NEON_DATA_API_URL||DATA_API_URL}${path}`,{...init,headers});if(!response.ok){const detail=await response.text().catch(()=> '');console.error('[monthly-champion-snapshot] Data API error:',response.status,detail.slice(0,300));throw new Error('Data API request failed')}const text=await response.text();return(text?JSON.parse(text):null) as T}
function jsonResponse(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{...CORS_HEADERS,...NO_CACHE_HEADERS,'Content-Type':'application/json'}})}
async function computeQuizChampion(env:Env,year:number,month:number,start:string,end:string,authorization?:string):Promise<ChampionRow|null>{const scores=await neonRequest<Array<{user_id:string;nickname:string;club_name:string;score:number|null}>>(env,`/quiz_scores?select=user_id,nickname,club_name,score,correct_count,total_questions,created_at&created_at=gte.${encodeURIComponent(start)}&created_at=lt.${encodeURIComponent(end)}`,{},authorization);if(!scores.length)return null;const roles=await neonRequest<Array<{user_id:string;club:string|null}>>(env,'/user_roles?select=user_id,club&is_active=eq.true',{},authorization);const clubMap=new Map<string,string>();roles.forEach(r=>{if(r.club)clubMap.set(r.user_id,r.club)});const users=new Map<string,{nickname:string;club_name:string;total_score:number}>(),clubs=new Map<string,number>();for(const row of scores){const club=clubMap.get(row.user_id);const name=club?(CLUB_LABEL_MAP[club]||club):row.club_name;const u=users.get(row.user_id);if(!u)users.set(row.user_id,{nickname:row.nickname,club_name:name,total_score:row.score||0});else{u.total_score+=row.score||0;u.club_name=name;if(row.nickname)u.nickname=row.nickname}}for(const u of users.values())clubs.set(u.club_name,(clubs.get(u.club_name)||0)+u.total_score);const top=[...clubs.entries()].sort((a,b)=>b[1]-a[1])[0];if(!top)return null;const player=[...users.values()].sort((a,b)=>b.total_score-a.total_score)[0]||null;return{year,month,category:'quiz',club_key:top[0],club_label:top[0],value:top[1],extra:player?{topPlayerNickname:player.nickname,topPlayerClub:player.club_name,topPlayerScore:player.total_score}:null}}
async function computeMarathonChampion(env:Env,year:number,month:number,start:string,end:string,authorization?:string):Promise<ChampionRow|null>{const data=await neonRequest<Array<{student_club:string|null;book:string;chapter_start:number|null;chapter_end:number|null}>>(env,`/bible_marathon_entries?select=student_club,book,chapter_start,chapter_end,status,confirmed_at&status=eq.confirmed&confirmed_at=gte.${encodeURIComponent(start)}&confirmed_at=lt.${encodeURIComponent(end)}`,{},authorization);if(!data.length)return null;const sets=new Map<string,Set<string>>();data.forEach(e=>{if(!e.student_club)return;const s=e.chapter_start??1,en=e.chapter_end??s;if(!sets.has(e.student_club))sets.set(e.student_club,new Set());const set=sets.get(e.student_club)!;for(let c=s;c<=en;c++)set.add(`${e.book}:${c}`)});const ranked=[...sets.entries()].map(([club,set])=>({club,chapters:set.size})).sort((a,b)=>b.chapters-a.chapters);if(!ranked.length)return null;const top=ranked[0];return{year,month,category:'marathon',club_key:top.club,club_label:CLUB_LABEL_MAP[top.club]||top.club,value:top.chapters,extra:null}}
export async function handleMonthlyChampionSnapshot(request:Request,env:Env):Promise<Response>{if(request.method==='OPTIONS')return new Response('ok',{headers:{...CORS_HEADERS,...NO_CACHE_HEADERS}});try{const url=new URL(request.url),mode=url.searchParams.get('mode')||'latest',authorization=request.headers.get('Authorization')||undefined;if(mode==='finalize'){const year=Number.parseInt(url.searchParams.get('year')||'',10),month=Number.parseInt(url.searchParams.get('month')||'',10),start=url.searchParams.get('start'),end=url.searchParams.get('end');if(!year||!month||!start||!end)return jsonResponse({error:'year, month, start, end가 모두 필요합니다.'},400);const[q,m]=await Promise.all([computeQuizChampion(env,year,month,start,end,authorization),computeMarathonChampion(env,year,month,start,end,authorization)]);const rows=[q,m].filter((r):r is ChampionRow=>r!==null);if(rows.length)await neonRequest(env,'/club_monthly_champions',{method:'POST',headers:{Prefer:'resolution=ignore-duplicates,return=minimal'},body:JSON.stringify(rows)},authorization);const records=await neonRequest<ChampionRow[]>(env,`/club_monthly_champions?select=*&year=eq.${year}&month=eq.${month}`,{},authorization);return jsonResponse({year,month,records})}if(mode==='latest'){const results:Record<string,unknown>={};for(const category of ['quiz','marathon'] as const){const rows=await neonRequest<ChampionRow[]>(env,`/club_monthly_champions?select=*&category=eq.${category}&order=year.desc,month.desc&limit=1`,{},authorization);results[category]=rows[0]||null}return jsonResponse(results)}if(mode==='list'){const n=Number.parseInt(url.searchParams.get('limit')||'60',10),limit=Math.min(Number.isFinite(n)?n:60,200);const records=await neonRequest<ChampionRow[]>(env,`/club_monthly_champions?select=*&order=year.desc,month.desc&limit=${limit}`,{},authorization);return jsonResponse({records})}return jsonResponse({error:'알 수 없는 mode 입니다.'},400)}catch(error){return jsonResponse({error:error instanceof Error?error.message:'서버 오류'},500)}}
