import { useState } from 'react';
import { motion } from 'framer-motion';
import { supabase } from '@/lib/supabase';
import AuthGuard from '@/components/base/AuthGuard';

type Mode='plan'|'ideas';
type RunStep={time:string;action:string;owner:string;output:string};
type Workstream={name:string;goal:string;firstStep:string;owner:string};
type Risk={risk:string;trigger:string;response:string};
type CommandCenter={title:string;mission:string;keyDecisions:string[];runOfShow:RunStep[];workstreams:Workstream[];risks:Risk[];nextActions:string[];bibleRef:string};
type Idea={title:string;concept:string;goal:string;how:string;people:string;cost:string;materials:string;time:string;staff:string;difficulty:string;pros:string;cons:string;caution:string;tip:string};
const SAMPLES=['새학기 월례회 / 동아리 4팀 공연 / 새친구 캠페인','동아리 공연이 많은 월례회인데 시간이 자주 밀려','학생 참여가 낮아지고 있는 월례회를 다시 살리고 싶어'];
const IDEA_SAMPLES=['새친구가 자연스럽게 참여하는 월례회','동아리 공연과 캠페인을 함께 살리는 행사','예산 10만원 이하로 할 수 있는 프로그램'];

export default function EventIdeasAI(){
 const [mode,setMode]=useState<Mode>('plan');
 const [theme,setTheme]=useState(''); const [clubs,setClubs]=useState(''); const [campaign,setCampaign]=useState(''); const [budget,setBudget]=useState('소규모 (10만원 이하)');
 const [result,setResult]=useState<CommandCenter|null>(null); const [ideas,setIdeas]=useState<Idea[]>([]); const [loading,setLoading]=useState(false); const [error,setError]=useState('');
 const reset=()=>{setTheme('');setClubs('');setCampaign('');setResult(null);setIdeas([]);setError('');};
 const changeMode=(next:Mode)=>{setMode(next);reset();};
 const generate=async()=>{const topic=theme.trim();if(!topic||loading)return;setLoading(true);setError('');setResult(null);setIdeas([]);try{const {data,error:fnError}=await supabase.functions.invoke('nim-event-ideas',{body:{mode,topic,clubs:clubs.trim(),campaign:campaign.trim(),audience:'교회 학생회 사명자 운영팀',budget}});if(fnError||!data)throw new Error('AI 결과를 불러오지 못했어요.');if(mode==='ideas'){if(!Array.isArray(data.ideas)||!data.ideas.length)throw new Error('실행 가능한 아이디어를 만들지 못했어요.');setIdeas(data.ideas as Idea[]);}else{setResult(data as CommandCenter);}}catch(e){setError(e instanceof Error?e.message:'AI 결과를 불러오지 못했어요.')}finally{setLoading(false)}};
 const inputForm=(<div className="space-y-4"><div className="flex gap-2 overflow-x-auto pb-1 scrollbar-hide">{(mode==='plan'?SAMPLES:IDEA_SAMPLES).map(s=><button key={s} type="button" onClick={()=>setTheme(s)} className="shrink-0 rounded-full border border-amber-200 bg-background-100 px-3 py-2 text-xs font-semibold text-amber-700">{s}</button>)}</div><div className="bg-background-100 border border-background-200 rounded-[22px] p-5 md:p-7 shadow-sm"><div className="rounded-2xl bg-amber-50 border border-amber-100 p-4 mb-5"><p className="text-sm font-bold text-amber-950">{mode==='plan'?'현실성 → 참여도 → 운영 안정성 순서로 계획합니다.':'현실성 → 참여도 → 준비 난이도 → 비용 효율 → 독창성 순서로 아이디어를 평가합니다.'}</p></div><div className="space-y-4"><div><label className="block text-sm font-semibold text-foreground-700 mb-1.5">{mode==='plan'?'행사 목적·해결하고 싶은 문제':'원하는 행사 아이디어의 방향'}</label><textarea value={theme} onChange={e=>setTheme(e.target.value)} rows={3} maxLength={700} placeholder={mode==='plan'?'예: 새학기 학생들이 자연스럽게 친해지고 동아리 공연도 매끄럽게 이어지는 월례회':'예: 새친구와 기존 학생이 어색하지 않게 섞이는 프로그램'} className="w-full px-4 py-3.5 text-[15px] rounded-xl border border-background-200 bg-background-50 outline-none focus:border-amber-400 focus:ring-2 focus:ring-amber-100 resize-none text-foreground-950"/></div><div><label className="block text-sm font-semibold text-foreground-700 mb-1.5">대상·참여 동아리·공연</label><input value={clubs} onChange={e=>setClubs(e.target.value)} placeholder="예: 중고등 학생 40명 / 밴드·댄스·찬양" maxLength={250} className="w-full px-4 py-3 text-[15px] rounded-xl border border-background-200 bg-background-50 outline-none focus:border-amber-400 text-foreground-950"/></div><div><label className="block text-sm font-semibold text-foreground-700 mb-1.5">참여 목표·캠페인</label><textarea value={campaign} onChange={e=>setCampaign(e.target.value)} rows={2} maxLength={300} placeholder="예: 새친구 1명에게 먼저 말 걸기" className="w-full px-4 py-3 text-[15px] rounded-xl border border-background-200 bg-background-50 outline-none focus:border-amber-400 resize-none text-foreground-950"/></div><div><label className="block text-sm font-semibold text-foreground-700 mb-1.5">예산/제약</label><select value={budget} onChange={e=>setBudget(e.target.value)} className="w-full px-4 py-3 text-[15px] rounded-xl border border-background-200 bg-background-50 outline-none focus:border-amber-400 text-foreground-950"><option>소규모 (10만원 이하)</option><option>중간 (30만원 이하)</option><option>대규모 (50만원 이상)</option></select></div>{error&&<div className="rounded-xl bg-rose-50 border border-rose-200 p-3 text-sm text-rose-700">{error}</div>}<button type="button" onClick={generate} disabled={!theme.trim()||loading} className="w-full min-h-12 rounded-xl bg-amber-500 text-white text-[15px] font-bold disabled:opacity-40">{loading?'AI가 실행 가능성을 검토하는 중…':mode==='plan'?'실행 가능한 행사 기획 만들기':'실행 가능한 아이디어 4개 만들기'}</button></div></div></div>);
 const planResult=result&&<div className="space-y-4"><section className="rounded-[22px] bg-background-100 border border-background-200 p-5 md:p-7"><p className="text-xs font-bold text-amber-700">성공 기준</p><h2 className="text-xl md:text-2xl font-bold text-foreground-950 mt-1">{result.title}</h2><p className="text-sm text-foreground-700 leading-relaxed mt-2">{result.mission}</p><div className="grid sm:grid-cols-3 gap-2 mt-5">{result.keyDecisions.map((x,i)=><div key={i} className="rounded-xl bg-amber-50 border border-amber-100 p-3"><p className="text-[11px] font-bold text-amber-700">결정 {i+1}</p><p className="text-sm font-semibold text-foreground-800 mt-1">{x}</p></div>)}</div></section><section className="rounded-[22px] bg-background-100 border border-background-200 p-5 md:p-7"><h3 className="text-lg font-bold text-foreground-950 mb-4">실행 일정</h3>{result.runOfShow.map((s,i)=><div key={i} className="flex gap-3 rounded-xl border border-background-200 bg-background-50 p-3.5 mb-2"><span className="shrink-0 w-14 h-8 rounded-lg bg-sky-100 text-sky-700 text-[11px] font-bold flex items-center justify-center">{s.time}</span><div><p className="text-sm font-semibold text-foreground-900">{s.action}</p><p className="text-xs text-foreground-500 mt-1">담당 {s.owner} · 결과 {s.output}</p></div></div>)}</section><section className="rounded-[22px] bg-background-100 border border-background-200 p-5 md:p-7"><h3 className="text-lg font-bold text-foreground-950 mb-4">운영 워크스트림</h3><div className="grid md:grid-cols-2 gap-3">{result.workstreams.map((w,i)=><div key={i} className="rounded-xl border border-emerald-100 bg-emerald-50/60 p-4"><p className="font-bold text-foreground-900">{w.name}</p><p className="text-sm text-foreground-700 mt-2"><b>목표</b> {w.goal}</p><p className="text-sm text-foreground-700 mt-2"><b>첫 실행</b> {w.firstStep}</p><p className="text-xs text-foreground-500 mt-2">담당 {w.owner}</p></div>)}</div></section><section className="rounded-[22px] bg-background-100 border border-background-200 p-5 md:p-7"><h3 className="text-lg font-bold text-foreground-950 mb-4">돌발상황 대비</h3>{result.risks.map((r,i)=><div key={i} className="rounded-xl border border-rose-100 bg-rose-50/60 p-4 mb-2"><p className="text-sm font-bold text-foreground-900">{r.risk}</p><p className="text-xs text-foreground-600 mt-1">발생 신호 · {r.trigger}</p><p className="text-sm text-rose-800 mt-2"><b>대응</b> {r.response}</p></div>)}</section><button type="button" onClick={reset} className="w-full min-h-11 rounded-xl border border-background-200 bg-background-100 text-sm font-semibold text-foreground-700">새로 만들기</button></div>;
 const ideaResult=ideas.length>0&&<div className="space-y-3">{ideas.map((idea,i)=><article key={i} className="rounded-[22px] bg-background-100 border border-background-200 p-5 md:p-6"><div className="flex items-start justify-between gap-3"><div><span className="text-xs font-bold text-amber-700">추천 아이디어 {i+1}</span><h2 className="text-lg md:text-xl font-bold text-foreground-950 mt-1">{idea.title}</h2></div><span className="shrink-0 rounded-full bg-background-200 px-2.5 py-1 text-[11px] font-bold text-foreground-600">난이도 {idea.difficulty}</span></div><p className="text-sm text-foreground-700 leading-relaxed mt-3">{idea.concept}</p><div className="grid sm:grid-cols-2 gap-2 mt-4">{[['목표',idea.goal],['진행',idea.how],['예상 인원',idea.people],['비용',idea.cost],['준비물',idea.materials],['시간',idea.time],['필요 인력',idea.staff],['장점',idea.pros],['단점',idea.cons],['주의',idea.caution],['실행 팁',idea.tip]].map(([k,v])=><div key={k} className="rounded-xl bg-background-50 border border-background-200 p-3"><p className="text-[11px] font-bold text-foreground-500">{k}</p><p className="text-sm text-foreground-800 mt-1 leading-relaxed">{v}</p></div>)}</div></article>)}<button type="button" onClick={reset} className="w-full min-h-11 rounded-xl border border-background-200 bg-background-100 text-sm font-semibold text-foreground-700">새로 만들기</button></div>;
 return <AuthGuard minRole="assistant_zone_leader"><div className="min-h-screen bg-background-50"><div className="max-w-4xl mx-auto px-4 md:px-6 py-7 md:py-12 pb-28"><div className="text-center mb-6"><div className="inline-flex items-center justify-center w-16 h-16 rounded-[22px] bg-amber-100 border border-amber-200 mb-4"><i className="ri-command-line text-3xl text-amber-700"/></div><div className="inline-flex items-center gap-1.5 rounded-full bg-amber-50 px-3 py-1 text-[11px] font-bold text-amber-700 border border-amber-100 mb-3">사명자 전용</div><h1 className="text-2xl md:text-3xl font-bold text-foreground-950">행사 기획 AI</h1><p className="text-sm text-foreground-600 mt-2">현실적으로 실행할 수 있는 행사 기획과 아이디어를 나눠서 만듭니다.</p></div><div className="flex gap-2 mb-5"><button type="button" onClick={()=>changeMode('plan')} className={`flex-1 min-h-11 rounded-xl border text-sm font-bold ${mode==='plan'?'bg-amber-500 border-amber-500 text-white':'bg-background-100 border-background-200 text-foreground-600'}`}><i className="ri-route-line mr-1"/>행사 기획</button><button type="button" onClick={()=>changeMode('ideas')} className={`flex-1 min-h-11 rounded-xl border text-sm font-bold ${mode==='ideas'?'bg-amber-500 border-amber-500 text-white':'bg-background-100 border-background-200 text-foreground-600'}`}><i className="ri-lightbulb-line mr-1"/>행사 아이디어</button></div>{result?planResult:ideas.length?ideaResult:inputForm}</div></div></AuthGuard>;
}