import { useState } from 'react';
import { motion } from 'framer-motion';
import AuthGuard from '@/components/base/AuthGuard';
import { supabase } from '@/lib/supabase';

type Mode='plan'|'ideas';
type Form={purpose:string;audience:string;people:string;date:string;time:string;place:string;budget:string;staff:string;style:string;constraints:string};
type Plan={eventName:string;goal:string;concept:string;audience:string;schedule:string[];prepSchedule:string[];programs:string[];roles:string[];materials:string[];budget:string[];promotion:string[];checklist:string[];risks:{problem:string;response:string}[];aftercare:string[]};
type Idea={name:string;purpose:string;concept:string;how:string;participation:string;people:string;cost:string;materials:string;time:string;staff:string;difficulty:string;pros:string[];cons:string[];caution:string;tip:string};
const empty:Form={purpose:'',audience:'',people:'',date:'',time:'',place:'',budget:'',staff:'',style:'',constraints:''};

export default function EventIdeasEnhanced(){const [mode,setMode]=useState<Mode>('plan');const [form,setForm]=useState<Form>(empty);const [plan,setPlan]=useState<Plan|null>(null);const [ideas,setIdeas]=useState<Idea[]>([]);const [loading,setLoading]=useState(false);const [error,setError]=useState('');
 const set=(k:keyof Form,v:string)=>setForm(f=>({...f,[k]:v}));
 const reset=()=>{setPlan(null);setIdeas([]);setError('');};
 const generate=async()=>{if(!form.purpose.trim())return;setLoading(true);setError('');
  try{const {data,error:fnError}=await supabase.functions.invoke('nim-event-suite-v2',{body:{mode,form}});if(fnError||!data)throw new Error(fnError?.message||'AI 결과를 만들지 못했습니다.');if(mode==='plan')setPlan(data as Plan);else setIdeas(Array.isArray(data)?data:[]);}catch(e){setError(e instanceof Error?e.message:'AI 결과를 만들지 못했습니다.');}finally{setLoading(false)}
 };
 return <AuthGuard minRole="assistant_zone_leader"><div className="min-h-screen bg-background-50"><div className="mx-auto max-w-4xl px-4 py-7 md:px-6 md:py-12 pb-28"><header className="mb-6 text-center"><div className="mx-auto mb-4 flex h-16 w-16 items-center justify-center rounded-[22px] bg-amber-100 border border-amber-200"><i className="ri-command-line text-3xl text-amber-700"/></div><span className="inline-flex rounded-full border border-amber-200 bg-amber-50 px-3 py-1 text-[11px] font-black text-amber-700">사명자 실무도구</span><h1 className="mt-2 text-2xl md:text-3xl font-black text-foreground-950">행사 기획 AI</h1><p className="mt-2 text-sm text-foreground-600">현실성 → 참여도 → 운영 안정성 → 비용 효율 순으로 판단합니다.</p></header>
 <div className="mb-5 grid grid-cols-2 gap-2"><button onClick={()=>{setMode('plan');reset()}} className={`min-h-11 rounded-xl border text-sm font-bold ${mode==='plan'?'border-amber-500 bg-amber-500 text-white':'border-background-200 bg-background-100 text-foreground-700'}`}>행사 기획</button><button onClick={()=>{setMode('ideas');reset()}} className={`min-h-11 rounded-xl border text-sm font-bold ${mode==='ideas'?'border-amber-500 bg-amber-500 text-white':'border-background-200 bg-background-100 text-foreground-700'}`}>행사 아이디어</button></div>
 {(!plan&&!ideas.length)?<div className="rounded-[22px] border border-background-200 bg-background-100 p-5 md:p-7 shadow-sm"><div className="grid gap-4 md:grid-cols-2"><Field label="행사 목적 / 해결할 문제" value={form.purpose} onChange={v=>set('purpose',v)} placeholder="예: 새친구가 어색하지 않게 참여하고 동아리 공연 시간을 지키는 월례회" area/><Field label="대상" value={form.audience} onChange={v=>set('audience',v)} placeholder="예: 중고등 학생"/><Field label="예상 인원" value={form.people} onChange={v=>set('people',v)} placeholder="예: 40명"/><Field label="날짜" value={form.date} onChange={v=>set('date',v)} placeholder="예: 2026-09-05"/><Field label="시간" value={form.time} onChange={v=>set('time',v)} placeholder="예: 14:00-17:00"/><Field label="장소" value={form.place} onChange={v=>set('place',v)} placeholder="예: 교회 2층"/><Field label="예산" value={form.budget} onChange={v=>set('budget',v)} placeholder="예: 30만원"/><Field label="가능 인력" value={form.staff} onChange={v=>set('staff',v)} placeholder="예: 교사 2명 + 사명자 6명"/><Field label="분위기 / 스타일" value={form.style} onChange={v=>set('style',v)} placeholder="예: 밝고 참여형"/><Field label="추가 제약" value={form.constraints} onChange={v=>set('constraints',v)} placeholder="예: 준비 2주, 소음 제한" area/><div className="md:col-span-2">{error&&<div className="mb-3 rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{error}</div>}<button disabled={!form.purpose.trim()||loading} onClick={generate} className="w-full min-h-12 rounded-xl bg-amber-500 text-white font-bold disabled:opacity-40">{loading?'실행 가능성을 검토하는 중…':'실행 가능한 결과 만들기'}</button></div></div></div>:
 <motion.div initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} className="space-y-4">{plan&&<><Block title="행사 개요"><h2 className="text-xl font-black text-foreground-950">{plan.eventName}</h2><p className="mt-2 text-sm text-foreground-700">{plan.goal}</p><p className="mt-2 text-sm leading-relaxed text-foreground-700">{plan.concept}</p><p className="mt-3 rounded-xl bg-background-50 p-3 text-sm text-foreground-700">대상 · {plan.audience}</p></Block><ListBlock title="전체 일정" items={plan.schedule}/><ListBlock title="준비 일정" items={plan.prepSchedule}/><ListBlock title="프로그램 / 진행 순서" items={plan.programs}/><ListBlock title="역할 분담" items={plan.roles}/><ListBlock title="준비물" items={plan.materials}/><ListBlock title="예상 예산" items={plan.budget}/><ListBlock title="홍보 방법" items={plan.promotion}/><ListBlock title="운영 체크리스트" items={plan.checklist}/><div className="rounded-[22px] border border-rose-200 bg-rose-50 p-5"><h3 className="font-bold text-rose-800">예상 문제 · 대응</h3><div className="mt-3 space-y-3">{plan.risks.map((r,i)=><div key={i} className="rounded-xl bg-white/70 p-3"><p className="text-sm font-bold text-foreground-900">{r.problem}</p><p className="mt-1 text-sm text-rose-800">{r.response}</p></div>)}</div></div><ListBlock title="행사 종료 후 정리" items={plan.aftercare}/></>}{ideas.length>0&&<>{ideas.map((idea,i)=><article key={i} className="rounded-[22px] border border-background-200 bg-background-100 p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><span className="text-xs font-black text-amber-700">추천 {i+1}</span><h2 className="mt-1 text-xl font-black text-foreground-950">{idea.name}</h2></div><span className="rounded-full bg-background-200 px-2.5 py-1 text-[11px] font-bold text-foreground-600">난이도 {idea.difficulty}</span></div><p className="mt-3 text-sm leading-relaxed text-foreground-700">{idea.concept}</p><div className="mt-4 grid gap-2 sm:grid-cols-2">{Object.entries({목적:idea.purpose,진행:idea.how,참여:idea.participation,인원:idea.people,비용:idea.cost,준비물:idea.materials,시간:idea.time,인력:idea.staff,주의:idea.caution,실행팁:idea.tip}).map(([k,v])=><div key={k} className="rounded-xl border border-background-200 bg-background-50 p-3"><p className="text-[11px] font-bold text-foreground-500">{k}</p><p className="mt-1 text-sm text-foreground-800">{v}</p></div>)}</div><div className="mt-4 grid gap-2 sm:grid-cols-2"><div className="rounded-xl bg-emerald-50 p-3"><p className="text-xs font-bold text-emerald-700">장점</p>{idea.pros.map(x=><p key={x} className="mt-1 text-sm text-emerald-900">• {x}</p>)}</div><div className="rounded-xl bg-rose-50 p-3"><p className="text-xs font-bold text-rose-700">단점</p>{idea.cons.map(x=><p key={x} className="mt-1 text-sm text-rose-900">• {x}</p>)}</div></div></article>)}</> }<button onClick={reset} className="w-full min-h-11 rounded-xl border border-background-200 bg-background-100 text-sm font-bold text-foreground-700">새로 만들기</button></motion.div>}
 </div></div></AuthGuard>;
}
function Field({label,value,onChange,placeholder,area=false}:{label:string;value:string;onChange:(v:string)=>void;placeholder:string;area?:boolean}){return <label className="block"> <span className="mb-1.5 block text-sm font-bold text-foreground-800">{label}</span>{area?<textarea value={value} onChange={e=>onChange(e.target.value)} rows={3} placeholder={placeholder} className="w-full rounded-xl border border-background-200 bg-background-50 px-4 py-3.5 text-[16px] text-foreground-950 outline-none focus:border-amber-400 focus:ring-2 focus:ring-amber-100 resize-none"/>:<input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} className="w-full min-h-12 rounded-xl border border-background-200 bg-background-50 px-4 text-[16px] text-foreground-950 outline-none focus:border-amber-400"/>}</label>}
function Block({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-[22px] border border-background-200 bg-background-100 p-5 shadow-sm"><p className="text-xs font-black text-amber-700">{title}</p><div className="mt-2">{children}</div></section>}
function ListBlock({title,items}:{title:string;items:string[]}){return <Block title={title}><div className="space-y-2">{items.map((x,i)=><div key={i} className="rounded-xl bg-background-50 border border-background-200 p-3 text-sm leading-relaxed text-foreground-800">{x}</div>)}</div></Block>}
