import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { fetchMbtiResult } from '@/lib/nvidiaNim';
import type { MbtiResult } from '@/lib/nvidiaNim';
import { notifyUser } from '@/lib/mobileFeedback';

type Question={id:number;axis:string;question:string;icon:string;options:string[]};
const questions:Question[]=[
{id:1,axis:'action',question:'친구가 힘들어할 때 나는?',icon:'ri-heart-line',options:['바로 달려가서 위로한다','옆에서 조용히 기도해 준다','실질적인 해결책을 같이 찾아본다','편하게 털어놓을 때까지 기다려 준다']},
{id:2,axis:'mindset',question:'새로운 사명이 주어졌을 때?',icon:'ri-lightbulb-line',options:['일단 믿음으로 도전한다','기도하고 신중하게 준비한다','계획부터 세우고 체계적으로 접근한다','주변 사람들과 협력하며 시작한다']},
{id:3,axis:'leadership',question:'내가 생각하는 좋은 리더는?',icon:'ri-star-line',options:['앞에서 방향을 제시한다','먼저 섬기며 모범을 보인다','근거를 모아 현명하게 결정한다','사람들의 의견을 듣고 조율한다']},
{id:4,axis:'crisis',question:'큰 장애물이 생기면?',icon:'ri-shield-line',options:['정면으로 부딪힌다','무릎 꿇고 지혜를 구한다','대안을 찾아 우회한다','사람을 모아 함께 해결한다']},
{id:5,axis:'community',question:'모임에서 나는 주로?',icon:'ri-group-line',options:['분위기를 먼저 띄운다','한 사람의 이야기를 깊게 듣는다','전체 흐름과 시간을 관리한다','새로 온 사람을 먼저 챙긴다']},
{id:6,axis:'prayer',question:'기도할 때 가장 가까운 모습은?',icon:'ri-hand-heart-line',options:['열정적으로 소리 내어 기도한다','조용히 오래 머문다','기도제목을 적고 구체적으로 기도한다','다른 사람의 제목을 품고 기도한다']},
{id:7,axis:'discipline',question:'준비해야 할 일이 있을 때?',icon:'ri-task-line',options:['마감 직전 집중력이 최고다','하나씩 천천히 준비한다','체크리스트를 만든다','함께할 사람과 역할을 나눈다']},
{id:8,axis:'relationship',question:'친구와 의견이 다르면?',icon:'ri-chat-check-line',options:['내 생각을 분명하게 말한다','상대의 마음부터 듣는다','공통점을 찾아 합의한다','시간을 두고 다시 이야기한다']},
{id:9,axis:'faith',question:'믿음이 흔들리는 순간에는?',icon:'ri-sun-line',options:['말씀을 붙들고 바로 행동한다','혼자 조용히 하나님 앞에 선다','왜 그런지 원인을 정리한다','믿을 만한 사람에게 나눈다']},
{id:10,axis:'service',question:'행사 준비에서 가장 먼저 하는 일은?',icon:'ri-calendar-check-line',options:['전체 분위기와 핵심 목표를 잡는다','사람들의 필요를 확인한다','일정·준비물·예산을 정리한다','팀별 담당자를 정한다']},
{id:11,axis:'growth',question:'실수했을 때 나는?',icon:'ri-refresh-line',options:['바로 다시 도전한다','기도하며 마음을 추스른다','원인을 분석하고 고친다','누군가에게 피드백을 구한다']},
{id:12,axis:'mission',question:'신앙생활에서 가장 중요하게 느끼는 것은?',icon:'ri-compass-3-line',options:['믿음을 행동으로 옮기는 것','하나님과 깊이 머무는 것','꾸준히 좋은 습관을 만드는 것','사람과 함께 성장하는 것']},
];
const AXIS:Record<string,string>={action:'행동력',mindset:'도전·준비 균형',leadership:'리더십',crisis:'위기 대응',community:'공동체성',prayer:'기도 성향',discipline:'꾸준함',relationship:'관계 조율',faith:'믿음의 중심',service:'섬김과 운영',growth:'회복과 성장',mission:'사명 실행'};

export default function BibleMbti(){
 const [step,setStep]=useState(0);const [answers,setAnswers]=useState<string[]>([]);const [result,setResult]=useState<MbtiResult|null>(null);const [loading,setLoading]=useState(false);const [error,setError]=useState('');
 const answer=async(value:string)=>{if(loading)return;const next=[...answers];next[step]=value;setAnswers(next);setError('');if(step<questions.length-1){setStep(step+1);return;}setLoading(true);try{const r=await fetchMbtiResult(next);setResult(r);setStep(questions.length);}catch(e){setError(e instanceof Error?e.message:'결과를 만들지 못했어요. 다시 시도해주세요.')}finally{setLoading(false)}};
 const back=()=>{if(step>0&&!result){setAnswers(a=>a.slice(0,-1));setStep(s=>s-1);setError('')}};
 const reset=()=>{setStep(0);setAnswers([]);setResult(null);setError('')};
 const retry=async()=>{if(answers.length<questions.length)return;setLoading(true);setError('');try{setResult(await fetchMbtiResult(answers));}catch(e){setError(e instanceof Error?e.message:'결과를 만들지 못했어요.')}finally{setLoading(false)}};
 const share=async()=>{if(!result)return;const text=`나의 성경 인물 MBTI는 ${result.character}입니다. ${result.matchingPhrase}`;try{if(navigator.share)await navigator.share({title:'성경 인물 MBTI',text});else{await navigator.clipboard.writeText(text);notifyUser('결과가 클립보드에 복사됐어요.')}}catch{}}
 const progress=Math.min(100,Math.round((Math.min(step,questions.length)/questions.length)*100));
 return <div className="min-h-screen bg-background-50"><div className="max-w-2xl mx-auto px-4 md:px-6 py-8 md:py-14 pb-28">
  {!result?<>
   <div className="text-center mb-6"><div className="inline-flex items-center justify-center w-16 h-16 rounded-[20px] bg-accent-100 border border-accent-200 mb-4"><i className="ri-user-heart-line text-3xl text-accent-600"/></div><h1 className="text-2xl md:text-3xl font-bold text-foreground-950">성경 인물 MBTI</h1><p className="text-sm text-foreground-600 mt-2">12가지 질문으로 나의 신앙 성향을 돌아보고, 닮은 성경 인물을 찾아보세요.</p></div>
   <div className="mb-5"><div className="flex items-center justify-between text-xs text-foreground-500 mb-2"><span>{Math.min(step+1,questions.length)} / {questions.length}</span><span>{progress}%</span></div><div className="h-2 rounded-full bg-background-200 overflow-hidden"><div className="h-full rounded-full bg-accent-500 transition-all" style={{width:`${progress}%`}}/></div></div>
   <AnimatePresence mode="wait"><motion.div key={step} initial={{opacity:0,x:30}} animate={{opacity:1,x:0}} exit={{opacity:0,x:-30}} transition={{duration:.2}}>
    <div className="bg-background-100 border border-background-200 rounded-[22px] p-5 md:p-7 shadow-sm"><div className="flex items-center gap-3 mb-5"><div className="w-11 h-11 rounded-xl bg-accent-100 flex items-center justify-center shrink-0"><i className={`${questions[step].icon} text-xl text-accent-600`}/></div><div><p className="text-xs font-bold text-accent-600">{AXIS[questions[step].axis]||'신앙 성향'}</p><h2 className="text-lg md:text-xl font-bold text-foreground-950 mt-1">{questions[step].question}</h2></div></div><div className="space-y-2.5">{questions[step].options.map((option,i)=><button key={option} type="button" onClick={()=>answer(option)} disabled={loading} className="w-full min-h-14 rounded-2xl border border-background-200 bg-background-50 px-4 py-3 text-left text-sm md:text-base font-semibold text-foreground-800 hover:border-accent-300 hover:bg-accent-50 active:scale-[.99] transition-all disabled:opacity-50"><span className="inline-flex w-7 h-7 rounded-full bg-background-200 items-center justify-center mr-3 text-xs font-bold text-foreground-600">{String.fromCharCode(65+i)}</span>{option}</button>)}</div></div>
   </motion.div></AnimatePresence>
   {error&&<div className="mt-3 rounded-xl bg-rose-50 border border-rose-200 p-3 text-sm text-rose-700">{error}<button type="button" onClick={retry} className="ml-2 underline font-semibold">다시 시도</button></div>}
   <div className="flex justify-between mt-4"><button type="button" onClick={back} disabled={step===0||loading} className="min-h-11 px-4 rounded-full border border-background-200 bg-background-100 text-sm font-semibold text-foreground-600 disabled:opacity-30">← 이전</button><button type="button" onClick={reset} disabled={loading} className="min-h-11 px-4 rounded-full text-sm font-semibold text-foreground-500 disabled:opacity-30">처음부터</button></div>
  </>:<motion.div initial={{opacity:0,y:15}} animate={{opacity:1,y:0}} className="space-y-4">
    <section className="rounded-[24px] bg-gradient-to-br from-accent-500 to-primary-600 p-6 md:p-8 text-white"><p className="text-xs font-bold text-white/80">나와 닮은 성경 인물</p><h1 className="text-3xl md:text-4xl font-black mt-1">{result.character}</h1><p className="text-base md:text-lg font-semibold mt-3 leading-relaxed">{result.matchingPhrase}</p><p className="text-sm text-white/85 mt-3 leading-relaxed">{result.description}</p><div className="flex gap-2 mt-5"><button type="button" onClick={share} className="min-h-11 px-4 rounded-full bg-white/15 text-white text-sm font-bold">공유하기</button><button type="button" onClick={reset} className="min-h-11 px-4 rounded-full bg-white text-foreground-950 text-sm font-bold">다시 검사</button></div></section>
    <section className="bg-background-100 border border-background-200 rounded-[22px] p-5 md:p-7"><h2 className="text-lg font-bold text-foreground-950 mb-4">내 성향</h2><div className="space-y-3">{result.traits.map((trait)=><div key={trait.label}><div className="flex justify-between text-xs font-semibold text-foreground-700 mb-1"><span>{trait.label}</span><span>{Math.round(trait.value)}</span></div><div className="h-2.5 rounded-full bg-background-200 overflow-hidden"><div className="h-full rounded-full bg-accent-400" style={{width:`${Math.max(0,Math.min(100,trait.value))}%`}}/></div></div>)}</div></section>
    <section className="grid md:grid-cols-2 gap-4"><div className="bg-background-100 border border-background-200 rounded-[22px] p-5"><h2 className="font-bold text-foreground-950 mb-2">신앙생활에서의 적용</h2><p className="text-sm text-foreground-700 leading-relaxed">{result.lesson}</p></div><div className="bg-background-100 border border-background-200 rounded-[22px] p-5"><h2 className="font-bold text-foreground-950 mb-2">주의해서 볼 점</h2><p className="text-sm text-foreground-700 leading-relaxed">{result.challenge}</p></div></section>
    <section className="bg-primary-50 border border-primary-200 rounded-[22px] p-5"><p className="text-xs font-bold text-primary-600">오늘의 말씀</p><p className="text-sm md:text-base font-semibold text-foreground-800 mt-2 leading-relaxed">{result.bibleVerse}</p><p className="text-xs text-foreground-500 mt-3">함께하면 좋은 인물 · {result.bestWith}</p></section>
    {error&&<div className="rounded-xl bg-rose-50 border border-rose-200 p-3 text-sm text-rose-700">{error}</div>}<button type="button" onClick={retry} disabled={loading} className="w-full min-h-12 rounded-xl border border-background-200 bg-background-100 text-sm font-semibold text-foreground-700 disabled:opacity-50">{loading?'결과를 다시 만드는 중…':'AI 결과 다시 분석하기'}</button>
  </motion.div>}
  {loading&&<div className="fixed inset-0 z-50 bg-black/25 backdrop-blur-sm flex items-center justify-center p-4"><div className="w-full max-w-sm rounded-2xl bg-background-100 p-7 text-center shadow-xl"><div className="w-12 h-12 mx-auto rounded-full border-4 border-accent-200 border-t-accent-500 animate-spin"/><p className="text-base font-bold text-foreground-950 mt-4">답변을 바탕으로 성향을 분석하고 있어요</p><p className="text-sm text-foreground-600 mt-1">잠시만 기다려 주세요.</p></div></div>}
 </div></div>;
}