import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const GATEWAY = "https://ceearwcfvcbjhmkuuqzv.supabase.co/functions/v1/ai-gateway";
const CORS = { "Access-Control-Allow-Origin": "*", "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type", "Content-Type": "application/json" };
type Ref = { emotion: string; reference: string; book: string; chapter: number; verses: number[] };
const REFS: Ref[] = [
{emotion:"기쁨",reference:"시편 16:11",book:"PSA",chapter:16,verses:[11]},{emotion:"기쁨",reference:"시편 30:5",book:"PSA",chapter:30,verses:[5]},
{emotion:"감사",reference:"시편 107:1",book:"PSA",chapter:107,verses:[1]},{emotion:"감사",reference:"데살로니가전서 5:18",book:"1TH",chapter:5,verses:[18]},
{emotion:"설렘",reference:"전도서 3:11",book:"ECC",chapter:3,verses:[11]},{emotion:"설렘",reference:"이사야 43:19",book:"ISA",chapter:43,verses:[19]},
{emotion:"평안",reference:"시편 4:8",book:"PSA",chapter:4,verses:[8]},{emotion:"평안",reference:"빌립보서 4:7",book:"PHP",chapter:4,verses:[7]},{emotion:"평안",reference:"요한복음 14:27",book:"JHN",chapter:14,verses:[27]},
{emotion:"슬픔",reference:"고린도후서 1:3-4",book:"2CO",chapter:1,verses:[3,4]},{emotion:"슬픔",reference:"시편 42:11",book:"PSA",chapter:42,verses:[11]},{emotion:"슬픔",reference:"요한계시록 21:4",book:"REV",chapter:21,verses:[4]},
{emotion:"불안",reference:"시편 56:3-4",book:"PSA",chapter:56,verses:[3,4]},{emotion:"불안",reference:"마태복음 6:34",book:"MAT",chapter:6,verses:[34]},{emotion:"불안",reference:"빌립보서 4:6-7",book:"PHP",chapter:4,verses:[6,7]},
{emotion:"걱정",reference:"시편 37:5",book:"PSA",chapter:37,verses:[5]},{emotion:"걱정",reference:"베드로전서 5:7",book:"1PE",chapter:5,verses:[7]},{emotion:"걱정",reference:"누가복음 10:41-42",book:"LUK",chapter:10,verses:[41,42]},
{emotion:"두려움",reference:"디모데후서 1:7",book:"2TI",chapter:1,verses:[7]},{emotion:"두려움",reference:"이사야 41:10",book:"ISA",chapter:41,verses:[10]},
{emotion:"답답함",reference:"예레미야 33:3",book:"JER",chapter:33,verses:[3]},{emotion:"답답함",reference:"전도서 3:1",book:"ECC",chapter:3,verses:[1]},
{emotion:"화남",reference:"잠언 19:11",book:"PRO",chapter:19,verses:[11]},{emotion:"화남",reference:"에베소서 4:26",book:"EPH",chapter:4,verses:[26]},
{emotion:"지침",reference:"시편 127:2",book:"PSA",chapter:127,verses:[2]},{emotion:"지침",reference:"마태복음 11:28-29",book:"MAT",chapter:11,verses:[28,29]},
{emotion:"외로움",reference:"시편 68:6",book:"PSA",chapter:68,verses:[6]},{emotion:"외로움",reference:"히브리서 13:5",book:"HEB",chapter:13,verses:[5]},
{emotion:"무기력",reference:"누가복음 1:37",book:"LUK",chapter:1,verses:[37]},{emotion:"무기력",reference:"사도행전 20:24",book:"ACT",chapter:20,verses:[24]},
{emotion:"혼란",reference:"시편 25:4-5",book:"PSA",chapter:25,verses:[4,5]},{emotion:"혼란",reference:"야고보서 1:5",book:"JAS",chapter:1,verses:[5]},
{emotion:"후회",reference:"요한일서 1:9",book:"1JN",chapter:1,verses:[9]},{emotion:"후회",reference:"시편 51:17",book:"PSA",chapter:51,verses:[17]},
{emotion:"미안함",reference:"시편 32:1-2",book:"PSA",chapter:32,verses:[1,2]},{emotion:"미안함",reference:"히브리서 10:22",book:"HEB",chapter:10,verses:[22]},
{emotion:"희망",reference:"시편 39:7",book:"PSA",chapter:39,verses:[7]},{emotion:"희망",reference:"로마서 5:5",book:"ROM",chapter:5,verses:[5]},{emotion:"희망",reference:"예레미야 29:11",book:"JER",chapter:29,verses:[11]},
{emotion:"우울",reference:"시편 34:18",book:"PSA",chapter:34,verses:[18]},{emotion:"우울",reference:"시편 40:1-2",book:"PSA",chapter:40,verses:[1,2]},{emotion:"우울",reference:"이사야 61:3",book:"ISA",chapter:61,verses:[3]},
{emotion:"좌절",reference:"잠언 24:16",book:"PRO",chapter:24,verses:[16]},{emotion:"좌절",reference:"고린도후서 4:8-9",book:"2CO",chapter:4,verses:[8,9]},
{emotion:"용기",reference:"여호수아 1:9",book:"JOS",chapter:1,verses:[9]},{emotion:"용기",reference:"이사야 40:31",book:"ISA",chapter:40,verses:[31]}
];
const CRISIS=["자살","죽고싶","죽고 싶","자해","극단적","끝내고 싶","살기 싫","살기싫","목숨"];
const DEPRESS=["우울","무기력","공허","의욕","사는게","사는 게"];
const KW:Record<string,string>={"행복":"기쁨","좋":"기쁨","신나":"설렘","재미":"기쁨","감사":"감사","고마":"감사","슬프":"슬픔","눈물":"슬픔","속상":"슬픔","불안":"불안","긴장":"불안","걱정":"걱정","고민":"걱정","스트레스":"걱정","무서":"두려움","겁나":"두려움","답답":"답답함","막막":"답답함","화":"화남","짜증":"화남","열받":"화남","힘들":"지침","지쳤":"지침","피곤":"지침","외로":"외로움","혼자":"외로움","의미":"무기력","혼란":"혼란","모르겠":"혼란","후회":"후회","미안":"미안함","죄송":"미안함","희망":"희망","기대":"희망","설레":"설렘","우울":"우울","좌절":"좌절","실패":"좌절","용기":"용기","도전":"용기"};
const jr=(d:unknown,s=200)=>new Response(JSON.stringify(d),{status:s,headers:CORS});
async function fetchVerse(ref:Ref,ms:number){const c=new AbortController();const t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(`https://bible.helloao.org/api/kor_old/${ref.book}/${ref.chapter}.json`,{signal:c.signal,headers:{Accept:"application/json"}});if(!r.ok)throw 0;const d=await r.json();const a=d?.chapter?.content;if(!Array.isArray(a))throw 0;const out:string[]=[];for(const x of a){if(x?.type==="verse"&&typeof x.number==="number"&&ref.verses.includes(x.number)&&Array.isArray(x.content)){const s=x.content.filter((y:unknown)=>typeof y==="string").join(" ").trim();if(s)out.push(s)}}if(!out.length)throw 0;return out.join(" ").replace(/\s+/g," ").trim()}finally{clearTimeout(t)}}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:CORS});try{const {userText}=await req.json();const text=String(userText||"").trim();if(!text)return jr({error:"고민이나 감정을 입력해주세요."},400);const lower=text.toLowerCase();const crisis=CRISIS.some(k=>lower.includes(k));const depression=DEPRESS.some(k=>lower.includes(k))&&!crisis;const emotions=[...new Set(Object.entries(KW).filter(([k])=>text.includes(k)).map(([,v])=>v))].slice(0,3);const analyzed=emotions.length?emotions:["평안","희망"];const primary=analyzed[0];let picked:Ref|undefined;let verseText="";for(const ref of REFS.filter(r=>analyzed.includes(r.emotion)).sort(()=>Math.random()-.5)){try{verseText=await fetchVerse(ref,1200);picked=ref;break}catch{}}if(!picked){picked=REFS.find(r=>r.emotion==="평안")!;try{verseText=await fetchVerse(picked,900)}catch{verseText="오늘도 하나님께서 함께하시기를 바랍니다."}}
let recommendation="",practice="",prayers:string[]=[];try{const c=new AbortController();const timer=setTimeout(()=>c.abort(),4500);const r=await fetch(GATEWAY,{method:"POST",signal:c.signal,headers:{"Content-Type":"application/json",Authorization:req.headers.get("Authorization")||""},body:JSON.stringify({task:"bible-pick",messages:[{role:"system",content:"당신은 청소년을 위한 따뜻한 신앙 멘토입니다. 학생의 고민과 추천 성경구절을 정확히 연결해 답하세요. recommendation은 구절이 필요한 이유 2문장, practice는 오늘 할 수 있는 작은 행동 1가지, prayers는 상황을 반영한 짧은 기도 2개만 작성하세요. 한국어로만 작성하고 JSON만 반환하세요."},{role:"user",content:`학생의 고민: ${text.slice(0,1800)}\n주 감정: ${primary}\n추천 구절: ${picked.reference} - ${verseText}`}],temperature:.45,max_tokens:500})});const p=await r.json();clearTimeout(timer);const raw=String(p?.choices?.[0]?.message?.content||"").replace(/```json/gi,"").replace(/```/g,"").trim();const a=raw.indexOf("{"),b=raw.lastIndexOf("}");if(r.ok&&a>=0&&b>a){const x=JSON.parse(raw.slice(a,b+1));recommendation=String(x.recommendation||"").trim();practice=String(x.practice||"").trim();prayers=Array.isArray(x.prayers)?x.prayers.filter((v:unknown)=>typeof v==="string"&&v.trim()).slice(0,2):[]}}catch{}
if(!recommendation)recommendation=`지금 ${primary}한 마음 속에서도 하나님께서는 당신의 상황을 아세요. ${picked.reference} 말씀처럼 오늘의 마음을 주님께 맡기고 한 걸음씩 나아가 보세요.`;if(!practice)practice="오늘 이 말씀을 천천히 세 번 읽고, 마음에 남는 한 문장을 메모해 보세요.";if(prayers.length<2)prayers=["주님, 제 마음을 아시니 오늘도 붙들어 주세요.","제가 작은 믿음으로 한 걸음 내딛도록 인도해 주세요."];const crisisMessage=crisis?"지금 많이 힘드시겠어요. 혼자 견디지 말고 가까운 어른이나 선생님에게 바로 알려 주세요. 긴급하면 112 또는 119에 연락하고, 청소년전화 1388이나 자살예방상담전화 109에서도 도움을 받을 수 있어요.":depression?"요즘 많이 지쳐 있었다면 혼자 버티지 않아도 괜찮아요. 믿을 수 있는 어른이나 선생님에게 마음을 나눠 보세요.":undefined;return jr({verse:verseText,reference:picked.reference,recommendation,practice,prayers,analyzedEmotions:analyzed,primaryEmotion:primary,crisisMessage});}catch(e){console.error("bible-pick",e);return jr({error:"말씀을 준비하는 중 오류가 발생했어요. 잠시 후 다시 시도해주세요."},503)}});