import "jsr:@supabase/functions-js/edge-runtime.d.ts";
// Pin the shared router to this exact Git commit so Production cannot silently use an older cached router.
import { callQualityAI } from "https://raw.githubusercontent.com/gnhweb/gnhweb/981c05a704d5c4a214ed42743004572003a87cb9/supabase/functions/_shared/aiRouterQuality.ts";

const CORS_HEADERS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Content-Type":"application/json","Cache-Control":"no-store"};
const INTERNAL_KEYS=["GEMINI_API_KEY","GROQ_API_KEY","MISTRAL_API_KEY","CLOUDFLARE_API_TOKEN","OPENROUTER_API_KEY","CEREBRAS_API_KEY","SAMBANOVA_API_KEY","TOGETHER_API_KEY","COHERE_API_KEY","HUGGINGFACE_API_KEY","NVIDIA_KEY_FALLBACK","GITHUB_MODELS_API_KEY","LLM7_API_KEY","ZAI_API_KEY","DEEPSEEK_API_KEY","XAI_API_KEY"];
function bearer(req:Request){const v=req.headers.get("authorization")||"";return v.startsWith("Bearer ")?v.slice(7).trim():"";}
async function authorized(req:Request){const token=bearer(req);if(!token)return false;for(const n of INTERNAL_KEYS){const s=Deno.env.get(n);if(s&&token===s)return true;}for(const [n,s] of Object.entries(Deno.env.toObject()))if(n.startsWith("NVIDIA_KEY_")&&s&&token===s)return true;const url=Deno.env.get("SUPABASE_URL")||"",anon=Deno.env.get("SUPABASE_ANON_KEY")||"";if(!url||!anon)return false;const c=new AbortController(),t=setTimeout(()=>c.abort(),1500);try{const r=await fetch(`${url}/auth/v1/user`,{headers:{apikey:anon,Authorization:`Bearer ${token}`},signal:c.signal});return r.ok;}catch{return false;}finally{clearTimeout(t);}}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:CORS_HEADERS});if(req.method!=="POST")return new Response(JSON.stringify({error:"POST only"}),{status:405,headers:CORS_HEADERS});if(!(await authorized(req)))return new Response(JSON.stringify({error:"인증이 필요합니다."}),{status:401,headers:CORS_HEADERS});try{const body=await req.json();const messages=Array.isArray(body?.messages)?body.messages:[];if(!messages.length)return new Response(JSON.stringify({error:"messages is required"}),{status:400,headers:CORS_HEADERS});const out=await callQualityAI({task:typeof body?.task==="string"?body.task:"site-ai",messages,temperature:Number.isFinite(Number(body?.temperature))?Number(body.temperature):0.32,maxTokens:Number.isFinite(Number(body?.max_tokens))?Number(body.max_tokens):1800});const h=new Headers(out.headers);Object.entries(CORS_HEADERS).forEach(([k,v])=>h.set(k,v));return new Response(out.body,{status:out.status,headers:h});}catch(e){console.error("[ai-gateway]",e);return new Response(JSON.stringify({error:"AI가 질문에 적절한 고품질 답변을 만들지 못했습니다. 잠시 후 다시 시도해주세요."}),{status:503,headers:CORS_HEADERS});}});
